### ISSUE TITLE
Unintended behavior in sunpy.net.Fido when downloading from CDAweb

### ISSUE THREAD

**Issue by nmiles2718** [sunpy/sunpy#6369] opened 2022-08-17 17:42 UTC
### Describe the bug

I went to download a few days worth of data from STEREO A using the CDAweb capabilities in the `Fido` class in the `sunpy.net` module. Instead of pulling down the data for the days I'm interested in, it downloaded the entire year. The download was quick, but that wont always be the case and I also don't think this is the intended behavior. 

Running the example using Solar Orbiter data worked fine and it downloaded only the data files for days in the date range I provided.

### To Reproduce

MWE
------
```python
import cdflib
from sunpy.net import Fido
from sunpy.net import attrs
from sunpy.timeseries import TimeSeries
sta_dataset = 'STA_L2_MAGPLASMA_1M' 
start_date = '2010/07/18'
stop_date = '2010/07/20'

trange = attrs.Time(start_date, stop_date)
cda_dataset = attrs.cdaweb.Dataset(sta_dataset)
result = Fido.search(trange, cda_dataset)
msg = (
    f"{result['cdaweb']['Start time']}\n{result['cdaweb']['End time']}\n"
    f"Found {len(result)} data products"
)
print(msg)
downloaded_files = Fido.fetch(result, overwrite=False, progress=False)
print('\n'.join(downloaded_files))
cdf = cdflib.CDF(downloaded_files[0])
dates = cdflib.epochs.CDFepoch.to_datetime(cdf['Epoch'])
print(min(dates), max(dates))
```

### Screenshots

![Screen Shot 2022-08-17 at 10 29 54 AM](https://user-images.githubusercontent.com/20194427/185204278-0daf1571-0103-40b3-aa7f-19b71dfb5a3e.png)

### System Details

```python
In [2]: sunpy.util.system_info()
==============================
sunpy Installation Information
==============================

General
#######
OS: Mac OS 10.16
Arch: 64bit, (i386)
sunpy: 4.0.4
Installation path: /Users/ndmiles/miniconda3/envs/ife/lib/python3.8/site-packages/sunpy-4.0.4.dist-info

Required Dependencies
#####################
astropy: 5.1
numpy: 1.23.2
packaging: 21.3
parfive: 2.0.1

Optional Dependencies
#####################
asdf: 2.12.0
asdf-astropy: 0.2.1
beautifulsoup4: 4.11.1
cdflib: 0.4.4
dask: 2022.8.0
drms: 0.6.2
glymur: 0.11.2
h5netcdf: 0.0.0
h5py: 3.7.0
matplotlib: 3.5.3
mpl-animators: 1.1.0
pandas: 1.4.3
python-dateutil: 2.8.2
reproject: 0.8
scikit-image: 0.19.3
scipy: 1.9.0
sqlalchemy: 1.4.40
tqdm: 4.64.0
zeep: 4.1.0

```

### Installation method

conda

**Comment by dstansby** [comment] 2022-08-17 17:50
👋 thanks for opening your first @sunpy issue, and for making it super detailed and therefore helpful!

I think this is the intended behaviour, because the files for the data products you're downloading contain a whole years worth of data (e.g. see https://spdf.gsfc.nasa.gov/pub/data/stereo/ahead/l2/merged/ for a file listing). The CDAWEB client returns any files that have data within the time interval you specify in the search, which is exactly what seems to be happening. So I'm going to close this - if any of that doesn't make sense or you still think I've got it wrong, drop another comment and I can reopen the issue 😄

**Closed by dstansby** 2022-08-17 17:50 UTC

**Comment by candeynasa** [comment] 2022-08-22 15:08
SPDF recommends using the CDAWeb REST "Get Data" call for retrieving just the selected variables and time range in a CDF data file that is generated on the fly https://cdaweb.gsfc.nasa.gov/WebServices/REST/ , rather than using the "Get Original Data" call that seems to be used in the issue. This would require adding a call to get the variable names in the selected datasets, similar to the calls for observatories and datasets for the selected observatories.  This resulting generated CDF has the added benefit of automatically including the latest metadata as stored in the master CDFs (otherwise it's useful to open the corresponding master CDF https://spdf.gsfc.nasa.gov/pub/software/cdawlib/0MASTERS/ first to populate metadata before reading the individual data files).  There is an option for getting all variables (ALL_VARIABLES) for the selected times, if restricting the variable list is not desired.
