### ISSUE TITLE
sunpy.physics.differential_rotation should loudly proclaim it does not work with cutouts

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#4972] opened 2021-02-09 19:55 UTC
See #3323. 

Differentially rotating cutouts using this old method does not work. This could should be deprecated and removed anyway in favor of `RotatedSunFrame`, but in the meantime, we should at least throw an error when a user throws in a cutout or if we cannot reliably detect this, we need a big red banner that proclaims this does not work with cutouts.

As it stands, it gives wrong and confusing results.

**Comment by ayshih** [comment] 2021-02-10 15:48
See https://github.com/sunpy/sunpy/issues/3323#issuecomment-776805110 for my objection

**Comment by ayshih** [comment] 2021-02-10 15:49
Re `RotatedSunFrame`, I'll cross-reference #3931

**Comment by ayshih** [comment] 2021-02-11 15:29
Closing as not a bug.  See https://github.com/sunpy/sunpy/issues/3323#issuecomment-777575463

**Closed by ayshih** 2021-02-11 15:29 UTC
Labels: physics
