### ISSUE TITLE
0.6.1: `python setup.py test` fails

### ISSUE THREAD

**Issue by olebole** [sunpy/sunpy#1622] opened 2015-12-14 09:52 UTC
Hi,

I am currently packaging sunpy for Debian. However, I failed running the tests:
```
$ python setup.py test
Unexpected output from `git submodule status`:

Will attempt import from 'astropy_helpers' regardless.
running test
running build
running build_py
running egg_info
writing requirements to sunpy.egg-info/requires.txt
writing sunpy.egg-info/PKG-INFO
writing top-level names to sunpy.egg-info/top_level.txt
writing dependency_links to sunpy.egg-info/dependency_links.txt
reading manifest file 'sunpy.egg-info/SOURCES.txt'
writing manifest file 'sunpy.egg-info/SOURCES.txt'
copying sunpy/_compiler.c -> build/lib.linux-x86_64-2.7/sunpy
running build_ext
Traceback (most recent call last):
  File "setup.py", line 136, in <module>
    **package_info
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/oles/Projects/2011/debian/python/sunpy/.eggs/astropy_helpers-1.0.6-py2.7.egg/astropy_helpers/test_helpers.py", line 150, in run
    self._build_temp_install()
  File "/home/oles/Projects/2011/debian/python/sunpy/.eggs/astropy_helpers-1.0.6-py2.7.egg/astropy_helpers/test_helpers.py", line 207, in _build_temp_install
    os.path.basename(self.docs_path))
  File "/usr/lib/python2.7/posixpath.py", line 114, in basename
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
```

When I try to use the latest astropy_helpers 1.1, I get
```
$ python setup.py test
/usr/lib/python2.7/dist-packages/astropy_helpers/setup_helpers.py:102: AstropyDeprecationWarning: Direct use of the adjust_compiler function in setup.py is deprecated and can be removed from your setup.py.  This functionality is now incorporated directly into the build_ext command.
  'command.', AstropyDeprecationWarning)
running test
running build
running build_py
running egg_info
writing requirements to sunpy.egg-info/requires.txt
writing sunpy.egg-info/PKG-INFO
writing top-level names to sunpy.egg-info/top_level.txt
writing dependency_links to sunpy.egg-info/dependency_links.txt
reading manifest file 'sunpy.egg-info/SOURCES.txt'
writing manifest file 'sunpy.egg-info/SOURCES.txt'
copying sunpy/_compiler.c -> build/lib.linux-x86_64-2.7/sunpy
running build_ext
Traceback (most recent call last):
  File "setup.py", line 136, in <module>
    **package_info
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/astropy_helpers/commands/_test_compat.py", line 165, in run
    self._build_temp_install()
  File "/usr/lib/python2.7/dist-packages/astropy_helpers/commands/_test_compat.py", line 216, in _build_temp_install
    dir=self.temp_root)
  File "/usr/lib/python2.7/distutils/cmd.py", line 105, in __getattr__
    raise AttributeError, attr
AttributeError: temp_root
```

**Comment by Cadair** [comment] 2015-12-14 09:58
Hey @olebole,

Thanks for taking on SunPy as a package.

I can't understand the astropy_helpers 1.0.6 error (I haven't tested with 1.1, I know they changed some stuff wrt to testing in 1.1).

Are you building from the tarball? Is there anything else different about your build env?

**Comment by olebole** [comment] 2015-12-14 11:07
I used the pypi tarball, and I think the rest is quite standard. Astropy version is 1.0.5 (also tested with 1.1).

**Comment by dpshelio** [comment] 2015-12-30 18:30
I'm getting the same error with astropy_helpers 1.1.1 and numpy 1.8.1.  If I update numpy then I get other problems with the compilation of ana reader.

**Comment by olebole** [comment] 2016-01-12 09:47
Hi,

is there any progress with that? The issue actually prevents me from creating a package, and the deadline for the inclusion in Ubuntu 16.04 is coming closer...

**Comment by Cadair** [comment] 2016-01-12 10:39
Hi @olebole I am still having issues replicating this, can you give me a list of all the packages and versions you have in your build env so I can see if I can reproduce?

**Comment by Cadair** [comment] 2016-01-12 10:41
@olebole Can you succesfully run the core tests with: `py.test sunpy -k-figure -k-online` ??

**Comment by Cadair** [comment] 2016-01-12 10:45
edit above with better command.

**Comment by olebole** [comment] 2016-01-12 10:58
Here is the list of packages that are currently installed (on Debian unstable):

| Name | Version |
|------|---------|
| python |2.7.11 |
| python-setuptools  | 18.8 |
| python-numpy | 1.10.4 |
| python-astropy | 1.1 |
| python-astropy-helpers | 1.1.1 |
| python-matplotlib | 1.5.1~rc1 |
| python-pytest | 2.8.5 |
| python-sqlalchemy | 1.0.11+ds1 |
| python-suds | 0.4.1 |
| python-pandas | 0.17.1 |
| python-bs4 | 4.4.1 |

**Comment by olebole** [comment] 2016-01-12 11:07
With pytest, it works better; I get some test failures. I will put them into a new Issue to keep this one to the "python setup.py test" issue.

**Comment by Cadair** [comment] 2016-01-12 11:35
@olebole I will spin up a debain unstable VM and see what I can do.

**Comment by olebole** [comment] 2016-01-12 12:04
It is not urgent anymore since I can live with the `py.test` command.

**Comment by pllim** [comment] 2016-03-29 21:06
I have the exact same error after applying the package template to Ginga via ejeschke/ginga#313. Found this on Google and wondering if you ever found out how to get rid of the error. I can't reproduce this error locally.

**Comment by Cadair** [comment] 2016-03-30 08:27
I think this is now fixed in 0.6.3? or @pllim are you getting this in master?

**Comment by olebole** [comment] 2016-03-30 09:04
I am handicapped with my test setup since sunpy does not compile on Debian unstable in the moment -- due to the issues with the numpy betas (#1653), and also not on Debian testing since pandas are not there (due to a number of issues). When it goes back to work, I can check as well.

**Comment by pllim** [comment] 2016-03-30 13:22
@Cadair , I pulled the template off GitHub yesterday, so pretty sure it is master. My suspicion (as I thought about it before I fell asleep; yes, I have no life) is that maybe some of the subpackage directories are missing `tests` folders. I'll see if that is the case today... Will keep you updated.

**Comment by Cadair** [comment] 2016-03-30 13:33
@pllim Did you get the error in SunPy? or did you not try? I think I fixed this I will investigate.

**Comment by pllim** [comment] 2016-03-30 13:35
Sorry for the confusion. I am not using SunPy. I have this same error with Ginga, so I was just wondering if you found a solution to this particular error on your end. I hope this clarifies things up...

**Comment by Cadair** [comment] 2016-03-30 13:38
I think it was this commit that fixed it for us: https://github.com/sunpy/sunpy/commit/b87b121d5dccd8a43c92dbdd54bd13c47f8a8bf0

**Closed** 2016-03-30 13:38 UTC

**Comment by pllim** [comment] 2016-03-30 15:42
Thanks, @Cadair . Based on your commit, I traced my problem to the package template not being able to handle documentation stored in `doc` instead of `docs`. I'll ask the template people.

**Comment by Cadair** [comment] 2016-03-30 15:59
@pllim we have that as well. You have to change the paths in setup.cfg iirc

**Comment by pllim** [comment] 2016-03-30 16:04
Yeah, I did. And I don't see anything that I missed comparing to your `setup.cfg`. However, SunPy uses its own `SunPyTest` class, which explicitly sets `self.docs_path` to the correct `os.path.abspath('doc')`, and the latest template uses `AstropyTest` from helpers, that defaults to `docs`. I have no idea how to customize the test runner without having to rewrite the helper stuff.

**Comment by pllim** [comment] 2016-03-30 16:05
When I make a `docs` symlink to `doc` and run the tests, I get this:

```
collected 99 items
================ 99 passed, ...
```

**Comment by Cadair** [comment] 2016-03-30 16:52
ah, yeah that would be a astropy/astropy-helpers issue then I guess.
