### ISSUE TITLE
Source tests are needed in the map factory test.

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#2055] opened 2017-03-26 17:25 UTC
See
https://github.com/sunpy/sunpy/blob/master/sunpy/map/tests/test_map_factory.py
There are a lot of missing source tests.

**Comment by nitinkgp23** [comment] 2017-03-26 17:29
Taking up the issue. Will add the test for #2007 too.

**Comment by nabobalis** [comment] 2019-01-22 15:38
Duplicate of another issue #664

**Closed by nabobalis** 2019-01-22 15:38 UTC
Labels: Tests, map
