### ISSUE TITLE
Error pulling GOES/XRS data on Windows?

### ISSUE THREAD

**Issue by jwreep** [sunpy/sunpy#5300] opened 2021-05-03 21:18 UTC
### Description

I get an error (TypeError: cannot unpack non-iterable NotImplementedType object) pulling GOES/XRS data from SunPy on Windows using the code below.  This works with no issues on MacOS.  

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-400b67f69c2d> in <module>
      6 files = Fido.fetch(result)
      7 
----> 8 goes = timeseries.TimeSeries(files, concatenate=True, )
      9 goes = goes.truncate('2013-11-05 22:00','2013-11-05 23:00')

C:\ProgramData\Anaconda3\lib\site-packages\sunpy\timeseries\timeseries_factory.py in __call__(self, silence_errors, *args, **kwargs)
    404         for filepath in filepaths:
    405             try:
--> 406                 new_ts = self._check_registered_widgets(filepath=filepath, **kwargs)
    407                 new_timeseries.append(new_ts)
    408             except (NoMatchError, MultipleMatchError, ValidationFunctionError):

C:\ProgramData\Anaconda3\lib\site-packages\sunpy\timeseries\timeseries_factory.py in _check_registered_widgets(self, **kwargs)
    527         units = kwargs.pop('units', None)
    528         if filepath:
--> 529             data, meta, units = WidgetType._parse_file(filepath)
    530 
    531         # Now return a TimeSeries from the given file.

TypeError: cannot unpack non-iterable NotImplementedType object
```

### Expected vs Actual behavior

The files download on MacOS and can be analyzed without issue.

### Steps to Reproduce

```python
from sunpy.time import parse_time
from sunpy import timeseries
from sunpy.net import Fido, attrs as a

result = Fido.search(
    a.Time('2013/11/04 06:00', '2013/11/06 00:00'),
    a.Instrument.xrs,
) 
files = Fido.fetch(result)

goes = timeseries.TimeSeries(files, concatenate=True, ) 
goes = goes.truncate('2013-11-05 22:00','2013-11-05 23:00')
```

### System Details

==============================
SunPy Installation Information
==============================

#######
General
#######
Time : Monday, 03. May 2021 09:03PM UT
System : Windows
Processor : AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
Arch : 64bit
SunPy : 2.1.4
OS: Windows 10 10.0.19041 (AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD)

##################
Required Libraries
##################
Python: 3.8.3
NumPy: 1.20.1
SciPy: 1.6.2
matplotlib: 3.3.4
Astropy: 4.2.1
Pandas: 1.2.4
parfive: 1.3.0

#####################
Recommended Libraries
#####################
beautifulsoup: 4.9.3
PyQt4: NOT INSTALLED
PyQt5: 5.9.2
Zeep: 4.0.0
Sqlalchemy: 1.4.7
drms: 0.6.1

**Comment by nabobalis** [comment] 2021-05-03 21:22
Thanks for the report @jwreep. I will have to test this on a windows system. 

I do have a question tho, did the files download ok on windows and are openable directly? 

Normally that error occurs when the file download has failed in some manner and the files are corrupt or blank.

**Comment by jwreep** [comment] 2021-05-03 21:41
Looks like it to me.  I can load it with netcdf4, at least:

```
import netCDF4 as nc
fn = 'C:\\Users\\jeffr\\sunpy\\data\\sci_gxrs-l2-irrad_g15_d20131106_v0-0-0.nc'
ds = nc.Dataset(fn)
print(ds)
```

```
<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    Conventions: ACDD-1.3, Spase v2.2.6
    title: GOES 1-15 L2 XRS high-resolution Irradiances
    id:  
    summary: The X-ray flux product consists of reprocessed science-quality high-resolution X-ray solar measurements. The GOES X-Ray Sensor (XRS) measures in a short wavelength channel (XRS-A) with a nominal bandpass of 0.05 to 0.4 nm and in a longer wavelength channel (XRS-B) with a bandpass of 0.1 to 0.8 nm. 

For the given bandpass, the XRS response is based on a flat spectrum beginning with GOES-3. A true solar spectrum is assumed for GOES 1-2.

GOES 13-15 measurements are at 2-s cadence. 
GOES 1-12 measured at a 3-s cadence. 

For GOES 3-12, the XRS-A response was originally determined assuming a bandpass of 0.05 to 0.3 nm.
    keywords: NumericalData.MeasurementType.Irradiance
    keywords_vocabulary: SPASE: Space Physics Archive Search and Extract Data Model version 2.2.6, GCMD: NASA Global Change Master Directory (GCMD) Earth Science Keywords version 8.5
    naming_authority: gov.nesdis.noaa
    history: See algorithm information.
    source: GOES XRS counts
    processing_level: Level 2
    processing_level_description: Derived products
    license: These data may be redistributed and used without restriction. 
    acknowledgment: TBD
    metadata_link: 
    date_created:  
    creator_name: Erika Zetterlund, Janet Machol
    creator_type: person
    creator_institution: DOC/NOAA/NCEI/CCOG/STP
    creator_email: goesr.exis@noaa.gov
    creator_url: https://www.ncei.noaa.gov/
    institution: DOC/NOAA/NESDIS> U.S. Department of Commerce, National Oceanic and Atmospheric Administration, National Environmental Satellite, Data, and Information Services
    publisher_name: National Centers for Environmental Information
    publisher_type: institution
    publisher_institution: DOC/NOAA/NESDIS/NCEI
    publisher_email: goesr.exis@noaa.gov
    publisher_url: https://www.ncei.noaa.gov/
    references: README FOR SCIENCE QUALITY GOES 13-15 XRS DATA
    instrument: GOES 1-15 X-ray Irradiance Sensor (XRS)
    instrument_id:  
    orbital_slot:  
    program: Geostationary Operational Environmental Satellite (GOES)
    project: Geostationary Operational Environmental Satellite (GOES) Solar Terrestrial Physics at NCEI
    platform:  
    L1b_system_environment:  
    L1b_production_site:  
    time_coverage_start:  
    time_coverage_end:  
    time_coverage_resolution: PT2S
    processing_parameters_file:  
    algorithm: 
    algorithm_version:  
    algorithm_date:  
    algorithm_parameters: None
    input_system_environments:  
    input_files_first:  
    input_files_last:  
    input_files_total:  
    dimensions(sizes): time(42151)
    variables(dimensions): int32 a_counts(time), int32 b_counts(time), float32 a_flux(time), float32 b_flux(time), uint16 a_flags(time), uint16 b_flags(time), uint32 a_swpc_flags(time), uint32 b_swpc_flags(time), float64 time(time)
    groups: 
```

**Comment by nabobalis** [comment] 2021-05-04 13:55
So I installed python 3.9 from the windows store and created a clean env and installed sunpy (`pip install sunpy[all]`) and the code passed for me.

My system info after this.

```
#######
General
#######
Time : Tuesday, 04. May 2021 01:31PM UT
System : Windows
Processor : AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD
Arch : 64bit
SunPy : 2.1.4
OS: Windows 10 10.0.19041 (AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD)

##################
Required Libraries
##################
Python: 3.9.4
NumPy: 1.20.2
SciPy: 1.6.3
matplotlib: 3.4.1
Astropy: 4.2.1
Pandas: 1.2.4
parfive: 1.3.0

#####################
Recommended Libraries
#####################
beautifulsoup: 4.9.3
PyQt4: NOT INSTALLED
PyQt5: NOT INSTALLED
Zeep: 4.0.0
Sqlalchemy: 1.4.13
drms: 0.6.1
```

The files I had saved locally were:
```
sci_gxrs-l2-irrad_g13_d20131104_v0-0-0.nc
sci_gxrs-l2-irrad_g13_d20131105_v0-0-0.nc
sci_gxrs-l2-irrad_g13_d20131106_v0-0-0.nc
sci_gxrs-l2-irrad_g15_d20131104_v0-0-0.nc
sci_gxrs-l2-irrad_g15_d20131105_v0-0-0.nc
sci_gxrs-l2-irrad_g15_d20131106_v0-0-0.nc
```

Right now I am not sure what to suggest as the next step.

**Comment by jwreep** [comment] 2021-05-04 23:54
I tried this on a second Windows machine and get the same error

```
>>> goes = timeseries.TimeSeries(files, concatenate=True, )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Jeff\anaconda3\lib\site-packages\sunpy\timeseries\timeseries_factory.py", line 406, in __call__
    new_ts = self._check_registered_widgets(filepath=filepath, **kwargs)
  File "C:\Users\Jeff\anaconda3\lib\site-packages\sunpy\timeseries\timeseries_factory.py", line 529, in _check_registered_widgets
    data, meta, units = WidgetType._parse_file(filepath)
TypeError: cannot unpack non-iterable NotImplementedType object
``` 

This was from a fresh install using conda.  The new system's info:  
```
#######
General
#######
Time : Tuesday, 04. May 2021 11:50PM UT
System : Windows
Processor : Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
Arch : 64bit
SunPy : 2.1.4
OS: Windows 10 10.0.19041 (Intel64 Family 6 Model 158 Stepping 9, GenuineIntel)


##################
Required Libraries
##################
Python: 3.7.10
NumPy: 1.20.1
SciPy: 1.6.2
matplotlib: 3.3.4
Astropy: 4.2.1
Pandas: 1.2.4
parfive: 1.3.0


#####################
Recommended Libraries
#####################
beautifulsoup: 4.9.3
PyQt4: NOT INSTALLED
PyQt5: 5.9.2
Zeep: 4.0.0
Sqlalchemy: 1.4.7
drms: 0.6.1
```

It looks like the major difference is Python version?  Does timeseries require Python > 3.8 on Windows?

**Comment by nabobalis** [comment] 2021-05-05 08:17
Let me build it on 3.8 and try again.

**Comment by wtbarnes** [comment] 2021-05-05 16:35
@jwreep @nabobalis could you both do an `ls` on these files to compare their relative sizes? Maybe Jeff's are actually getting truncated and netCDF is ok with opening them while our file parser is not?

**Comment by nabobalis** [comment] 2021-05-05 16:48
```bash
❯ ls
total 4.8M
-rwxr--r-- 1 nabil nabil 819K May  5 11:30 sci_gxrs-l2-irrad_g13_d20131104_v0-0-0.nc
-rwxr--r-- 1 nabil nabil 831K May  5 11:30 sci_gxrs-l2-irrad_g13_d20131105_v0-0-0.nc
-rwxr--r-- 1 nabil nabil 839K May  5 11:30 sci_gxrs-l2-irrad_g13_d20131106_v0-0-0.nc
-rwxr--r-- 1 nabil nabil 766K May  5 11:30 sci_gxrs-l2-irrad_g15_d20131104_v0-0-0.nc
-rwxr--r-- 1 nabil nabil 789K May  5 11:30 sci_gxrs-l2-irrad_g15_d20131105_v0-0-0.nc
-rwxr--r-- 1 nabil nabil 793K May  5 11:30 sci_gxrs-l2-irrad_g15_d20131106_v0-0-0.nc
```

**Comment by jwreep** [comment] 2021-05-05 17:14
```
 Directory of C:\Users\jeffr\sunpy\data

05/03/2021  05:27 PM    <DIR>          .
05/03/2021  05:27 PM    <DIR>          ..
05/03/2021  04:55 PM           838,089 sci_gxrs-l2-irrad_g13_d20131104_v0-0-0.nc
05/03/2021  04:55 PM           850,034 sci_gxrs-l2-irrad_g13_d20131105_v0-0-0.nc
05/03/2021  04:55 PM           858,211 sci_gxrs-l2-irrad_g13_d20131106_v0-0-0.nc
05/03/2021  04:55 PM           784,101 sci_gxrs-l2-irrad_g15_d20131104_v0-0-0.nc
05/03/2021  04:55 PM           807,774 sci_gxrs-l2-irrad_g15_d20131105_v0-0-0.nc
05/03/2021  04:55 PM           811,979 sci_gxrs-l2-irrad_g15_d20131106_v0-0-0.nc
              10 File(s)      8,083,750 bytes
               2 Dir(s)  214,595,301,376 bytes free
```

**Comment by AdamJamesFinley** [comment] 2021-05-10 11:16
I have the same error message on a mac operating system. The files download just fine, but sunpy fails to create the timeseries object from them. (TypeError: cannot unpack non-iterable NotImplementedType object)

**Comment by AdamJamesFinley** [comment] 2021-05-10 11:47
I get the same error if I use one file e.g. goes = ts.TimeSeries(".../sunpy/data/sci_xrsf-l2-flx1s_g17_d20210505_v2-1-0.nc"). My sunpy is ""sunpy                     2.1.1 "".

**Comment by nabobalis** [comment] 2021-05-10 12:02
Can you try adding `source='XRS'` to the `ts.TimeSeries` call? I don't think it will change anything but I want to check.

**Comment by AdamJamesFinley** [comment] 2021-05-10 12:07
I have already tried this, it doesn't change the outcome.

**Comment by nabobalis** [comment] 2021-05-10 12:13
Thanks, can you upload a file you downloaded? I've been unable to replicate this locally and maybe if I start with a file, maybe that will help.

Can you also tell me the version of "h5netcdf" and "h5py" you have installed?

**Comment by hayesla** [comment] 2021-05-10 12:23
This is same as  https://github.com/sunpy/sunpy/issues/5076 as far as I can tell?

**Comment by AdamJamesFinley** [comment] 2021-05-10 12:24
[sci_xrsf-l2-flx1s_g17_d20210504_v2-1-0.nc.zip](https://github.com/sunpy/sunpy/files/6451946/sci_xrsf-l2-flx1s_g17_d20210504_v2-1-0.nc.zip)

**Comment by AdamJamesFinley** [comment] 2021-05-10 12:25
h5py                      2.10.0
h5netcdf                  0.10.0

**Comment by nabobalis** [comment] 2021-05-10 12:29
> This is same as #5076 as far as I can tell?

Ah I forgot about this!

@AdamJamesFinley can you try updating h5py? `pip install -U h5py` should be the command.

**Comment by nabobalis** [comment] 2021-05-10 12:53
Hi @jwreep, can you do the same and see if that fixes it? `pip install -U h5py`

**Comment by nabobalis** [comment] 2021-05-10 18:28
Thanks for confirming that, we will patch sunpy to force a higher version of that package.

**Comment by jwreep** [comment] 2021-05-12 19:15
@nabobalis Perhaps we're not out of the woods yet.  I tried pulling all of the XRS data that overlapped with MinXSS-1 and ran into the same error again.  This time I have the most up-to-date sunpy and h5py.

```python
result = Fido.search(
    a.Time('2016/06/09 00:00', '2017/04/26 00:00'),
    a.Instrument.xrs, a.goes.SatelliteNumber(15)
) 
files = Fido.fetch(result)

goes = timeseries.TimeSeries(files, concatenate=True, ) 
```

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-e8dfdf462da9> in <module>
      6 files = Fido.fetch(result)
      7 
----> 8 goes = timeseries.TimeSeries(files, concatenate=True, )

~/anaconda3/lib/python3.8/site-packages/sunpy/timeseries/timeseries_factory.py in __call__(self, silence_errors, *args, **kwargs)
    404         for filepath in filepaths:
    405             try:
--> 406                 new_ts = self._check_registered_widgets(filepath=filepath, **kwargs)
    407                 new_timeseries.append(new_ts)
    408             except (NoMatchError, MultipleMatchError, ValidationFunctionError):

~/anaconda3/lib/python3.8/site-packages/sunpy/timeseries/timeseries_factory.py in _check_registered_widgets(self, **kwargs)
    527         units = kwargs.pop('units', None)
    528         if filepath:
--> 529             data, meta, units = WidgetType._parse_file(filepath)
    530 
    531         # Now return a TimeSeries from the given file.

TypeError: cannot unpack non-iterable NotImplementedType object
```

```
==============================
SunPy Installation Information
==============================

#######
General
#######
Time : Wednesday, 12. May 2021 02:07PM UT
System : Darwin
Processor : i386
Arch : 64bit
SunPy : 2.1.4
OS: Mac OS X 10.13.6 (i386)


##################
Required Libraries
##################
Python: 3.8.5
NumPy: 1.20.3
SciPy: 1.6.3
matplotlib: 3.4.2
Astropy: 4.2.1
Pandas: 1.2.4
parfive: 1.3.0


#####################
Recommended Libraries
#####################
beautifulsoup: 4.9.3
PyQt4: NOT INSTALLED
PyQt5: 5.9.2
Zeep: 4.0.0
Sqlalchemy: 1.3.20
drms: 0.6.1
```

**Comment by nabobalis** [comment] 2021-05-12 19:34
I ran that and also hit that issue (using sunpy master):

The error looks like:
```python
NoMatchError: Could not find any timeseries sources to parse /home/nabil/sunpy/data/sci_gxrs-l2-irrad_g15_d20161107_v0-0-0.nc
```
now.

**Comment by jwreep** [comment] 2021-05-12 19:53
In the nc files?  I don't see that.  For me it failed on 20161119 (which is a blank file), and the previous few files that finished downloading (e.g. 20161117) look fine to me.

**Comment by nabobalis** [comment] 2021-05-12 19:54
I wonder why that one was blank. I assume that was the cause of the fail in your case?

**Comment by jwreep** [comment] 2021-05-12 19:58
Looks like that.  Well, it created the file but didn't actually download any of the data.  Perhaps NOAA (or wherever the data is downloaded from) blocks the downloader if there are too many requests in a short period of time?

**Comment by nabobalis** [comment] 2021-05-12 20:02
Yeah I am getting local timeouts trying to do the search several times and its quite slow for me.

The header on the nc file seems to suggest an issue with too many requests, we might need to lower the number of requests we make for that client of ours.

**Comment by jwreep** [comment] 2021-05-12 21:14
This isn't an elegant solution, but splitting the search up into chunks and pausing between each allowed it to run for me:

```python
datetimes = ['2016/06/09 00:00', '2016/07/01 00:00', '2016/08/01 00:00', '2016/09/01 00:00',
                  '2016/10/01 00:00','2016/11/01 00:00','2016/12/01 00:00','2017/01/01 00:00',
                  '2017/02/01 00:00','2017/03/01 00:00','2017/04/01 00:00', '2017/04/26 00:00', ]
all_files = []
for i in range(len(datetimes)-1):
    result = Fido.search(
        a.Time(datetimes[i], datetimes[i+1]),
        a.Instrument.xrs, a.goes.SatelliteNumber(15)
    ) 
    files = Fido.fetch(result)
    for j in range(len(files)):
        all_files.append(files[j])
    time.sleep(2)
    

goes = timeseries.TimeSeries(all_files, concatenate=True, ) 
goes = goes.truncate(datetimes[0], datetimes[-1])
```

The only caveat was that I had to delete the corrupted files first.

Perhaps in the source code itself a similar split could be done when the number of requested files is large?

**Comment by nabobalis** [comment] 2021-05-12 21:42
Thanks, that is something we need to fix within our own client.

**Comment by nabobalis** [comment] 2021-05-15 09:04
We made a slight change to increase the wait period between requests to a server if it timeouts on us. It was better behaved for me now. That should be in the new 3.0 release.

**Comment by shifanakoya** [comment] 2022-04-22 10:10
Hi I am relatively new to the community but I am facing a NoMatch error problem in GOES/XRS plot in sunpy

I am using the code here : https://docs.sunpy.org/en/stable/generated/gallery/time_series/goes_hek_m25.html
it downloads the file but during Timeseries conversion it shows an error.- NoMatchError: Could not find any timeseries sources to parse /home/shifana/sunpy/data/sci_gxrs-l2-irrad_g15_d20110607_v0-0-0.nc
This code was worked fine for me in the past now its not

**Comment by nabobalis** [comment] 2022-04-22 15:38
Hi @shifanakoya, can you show me the output from `sunpy.system_info`? 

When you run that example, can you print out the `files` variable?

**Comment by shifanakoya** [comment] 2022-04-22 18:23
Hi, it appeared an issue related to my sunpy version earlier I was using 3.1.1 now updated to 3.1.6 now this example works fine.
any way the files variable print as ['/home/shifana/sunpy/data/sci_gxrs-l2-irrad_g15_d20120712_v0-0-0.nc']

**Comment by nabobalis** [comment] 2022-04-27 17:36
I am going to close this, I think it was patched in the latest versions of sunpy. 

If anyone has any new problems please comment here or open a new issue!  Thanks.

**Closed by nabobalis** 2022-04-27 17:36 UTC
Labels: Bug, net, Priority High, timeseries

**Comment by shifanakoya** [comment] 2022-05-11 07:29
Hi
I would like to ask 2 things. I am using the code here: https://docs.sunpy.org/en/stable/generated/gallery/time_series/goes_hek_m25.html#sphx-glr-generated-gallery-time-series-goes-hek-m25-py
1) isn't recent dates can plot using the code I am trying for flare times from 2022-03-09 to 2022-03-11. In trials, it appears only up to 2019 that this code is downloading flies.

2) As I tried 2019-03-09 04:00 to 2019-03-11  11:00 it seems it downloaded a file but not plotting it
printing 
![Screenshot from 2022-05-11 10-27-49](https://user-images.githubusercontent.com/55286796/167793313-ccf4253a-7d64-4941-84f3-3029a07672df.png)

**Comment by shifanakoya** [comment] 2022-05-11 22:18
Hi thanks for the reply
but it seems the code is not able to retrieve `~sunpy.net.hek.HEKTable` from the Fido result
getting an error in that line. I replaced GOES numbers with 16 and 17 in which data is available for recent dates. I deleted the earlier files from the directory
![Screenshot from 2022-05-12 01-17-08](https://user-images.githubusercontent.com/55286796/167956639-218d48f4-4a0b-4028-b9f2-f9847ee33fdd.png)

**Comment by nabobalis** [comment] 2022-05-11 22:34
That error happened since there is no data in the results from HEK. 

Can I get a copy of the code you are running?

**Comment by shifanakoya** [comment] 2022-05-11 22:45
Hi here it is
"""
==============================
Flare times on a GOES XRS plot
==============================

How to plot flare times as provided by the HEK on a GOES XRS plot.
"""
import matplotlib.pyplot as plt

from sunpy.net import Fido
from sunpy.net import attrs as a
from sunpy.time import parse_time
from sunpy.timeseries import TimeSeries

###############################################################################
# Let's grab GOES XRS data for a particular time of interest and the HEK flare
# data for this time from the NOAA Space Weather Prediction Center (SWPC).

tr = a.Time('2022-03-09 04:00', '2022-03-11 12:00')
results = Fido.search(tr, a.Instrument.xrs & a.goes.SatelliteNumber(16) | a.hek.FL & (a.hek.FRM.Name == 'SWPC'))  # NOQA

###############################################################################
# Then download the XRS data and load it into a TimeSeries.

files = Fido.fetch(results)
goes = TimeSeries(files)

###############################################################################
# Next let's retrieve `~sunpy.net.hek.HEKTable` from the Fido result
# and then load the first row from HEK results into ``flares_hek``.

hek_results = results['hek']
print(hek_results)
flares_hek = hek_results[0]

###############################################################################
# Lets plot everything together.

plt.figure()
goes.plot()
plt.axvline(parse_time(flares_hek['event_peaktime']).datetime)
plt.axvspan(parse_time(flares_hek['event_starttime']).datetime,
            parse_time(flares_hek['event_endtime']).datetime,
            alpha=0.2, label=flares_hek['fl_goescls'])
plt.legend(loc=2)
plt.yscale('log')

plt.show()

**Comment by shifanakoya** [comment] 2022-05-11 22:46
`"""
==============================
Flare times on a GOES XRS plot
==============================

How to plot flare times as provided by the HEK on a GOES XRS plot.
"""
import matplotlib.pyplot as plt

from sunpy.net import Fido
from sunpy.net import attrs as a
from sunpy.time import parse_time
from sunpy.timeseries import TimeSeries

###############################################################################
# Let's grab GOES XRS data for a particular time of interest and the HEK flare
# data for this time from the NOAA Space Weather Prediction Center (SWPC).

tr = a.Time('2022-03-09 04:00', '2022-03-11 12:00')
results = Fido.search(tr, a.Instrument.xrs & a.goes.SatelliteNumber(16) | a.hek.FL & (a.hek.FRM.Name == 'SWPC'))  # NOQA

###############################################################################
# Then download the XRS data and load it into a TimeSeries.

files = Fido.fetch(results)
goes = TimeSeries(files)

###############################################################################
# Next let's retrieve `~sunpy.net.hek.HEKTable` from the Fido result
# and then load the first row from HEK results into ``flares_hek``.

hek_results = results['hek']
print(hek_results)
flares_hek = hek_results[0]

###############################################################################
# Lets plot everything together.

plt.figure()
goes.plot()
plt.axvline(parse_time(flares_hek['event_peaktime']).datetime)
plt.axvspan(parse_time(flares_hek['event_starttime']).datetime,
            parse_time(flares_hek['event_endtime']).datetime,
            alpha=0.2, label=flares_hek['fl_goescls'])
plt.legend(loc=2)
plt.yscale('log')

plt.show()`

**Comment by shifanakoya** [comment] 2022-05-11 22:47
`"""
==============================
Flare times on a GOES XRS plot
==============================

How to plot flare times as provided by the HEK on a GOES XRS plot.
"""
import matplotlib.pyplot as plt

from sunpy.net import Fido
from sunpy.net import attrs as a
from sunpy.time import parse_time
from sunpy.timeseries import TimeSeries

###############################################################################
# Let's grab GOES XRS data for a particular time of interest and the HEK flare
# data for this time from the NOAA Space Weather Prediction Center (SWPC).

tr = a.Time('2022-03-09 04:00', '2022-03-11 12:00')
results = Fido.search(tr, a.Instrument.xrs & a.goes.SatelliteNumber(16) | a.hek.FL & (a.hek.FRM.Name == 'SWPC'))  # NOQA

###############################################################################
# Then download the XRS data and load it into a TimeSeries.

files = Fido.fetch(results)
goes = TimeSeries(files)

###############################################################################
# Next let's retrieve `~sunpy.net.hek.HEKTable` from the Fido result
# and then load the first row from HEK results into ``flares_hek``.

hek_results = results['hek']
print(hek_results)
flares_hek = hek_results[0]

###############################################################################
# Lets plot everything together.

plt.figure()
goes.plot()
plt.axvline(parse_time(flares_hek['event_peaktime']).datetime)
plt.axvspan(parse_time(flares_hek['event_starttime']).datetime,
            parse_time(flares_hek['event_endtime']).datetime,
            alpha=0.2, label=flares_hek['fl_goescls'])
plt.legend(loc=2)
plt.yscale('log')

plt.show()`

**Comment by nabobalis** [comment] 2022-05-11 23:11
Try running:

```python
import matplotlib.pyplot as plt

from sunpy.net import Fido
from sunpy.net import attrs as a
from sunpy.time import parse_time
from sunpy.timeseries import TimeSeries

results = Fido.search(a.Time('2022-03-09 04:00', '2022-03-11 12:00'),
                      a.Instrument.xrs & a.goes.SatelliteNumber(16))

files = Fido.fetch(results)
goes = TimeSeries(files)
for goes_ts in goes:
    plt.figure()
    goes_ts.plot()
    plt.legend(loc=2)
    plt.yscale('log')
    plt.show()
```

**Comment by shifanakoya** [comment] 2022-05-12 08:26
Hi Thanks, this works but yes, the return from Timeseries(files) is a list. Hence as u have written a loop I am getting the 3 plots, how can I combine them so that to see the entire time range in 1 single plot?
Here is something I tried:

import matplotlib.pyplot as plt

from sunpy.net import Fido
from sunpy.net import attrs as a
from sunpy.time import parse_time
from sunpy.timeseries import TimeSeries

results = Fido.search(a.Time('2022-03-09 04:00', '2022-03-11 12:00'),
                      a.Instrument.xrs & a.goes.SatelliteNumber(16))

files = Fido.fetch(results)
goes = TimeSeries(files)
print((goes[0]))
print((goes_ts))
goes_ts.plot()
#for goes_ts in goes:
    #plt.figure()
    #goes_ts.plot()
    #plt.legend(loc=2)
    #plt.yscale('log')
plt.show()

The print out put are
<sunpy.timeseries.sources.goes.XRSTimeSeries object at 0x7faa14d90fd0>
<sunpy.timeseries.sources.goes.XRSTimeSeries object at 0x7faa14847fd0>

**Comment by nabobalis** [comment] 2022-05-12 15:46
Can you try doing `goes = TimeSeries(files, concatenate=true)` and seeing if that returns one timeseries?

**Comment by shifanakoya** [comment] 2022-05-12 15:52
that's returns a name error
NameError: name 'true' is not defined

**Comment by nabobalis** [comment] 2022-05-12 16:00
Sorry, true was meant to be True

**Comment by shifanakoya** [comment] 2022-05-12 16:10
> Can you try doing `goes = TimeSeries(files, concatenate=true)` and seeing if that returns one timeseries?

this also returns a list, and hence 3 separate plots

**Comment by nabobalis** [comment] 2022-05-12 17:51
I ran

```python
import matplotlib.pyplot as plt

from sunpy.net import Fido
from sunpy.net import attrs as a
from sunpy.time import parse_time
from sunpy.timeseries import TimeSeries

results = Fido.search(a.Time('2022-03-09 04:00', '2022-03-11 12:00'),
                      a.Instrument.xrs & a.goes.SatelliteNumber(16))

files = Fido.fetch(results)
goes = TimeSeries(files, concatenate=True)
goes.plot()
plt.show()
```

and got one plot:
![Figure_1](https://user-images.githubusercontent.com/1392107/168137689-8f9f9011-849b-4adb-ba3b-c18762ea80d9.png)


Is that what you are after?

**Comment by shifanakoya** [comment] 2022-05-12 18:00
Yaaay! Exactly! I also ran this code and got the results. yeap this is what I was looking for!
Thank you very much- thank you for your patience to help a beginner like me!
Thank u so much! we got it!!!!
