### ISSUE TITLE
Include units in HTML repr

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#5389] opened 2021-06-04 15:44 UTC
The units of a map are accessible via `.unit`. This is included in the `peek` colorbar, but not in the fancy html repr. It would be nice to include this too, maybe just as an additional entry in the table on the left.

**Comment by hayesla** [comment] 2021-06-04 15:46
snap again #5388 5388

**Comment by nabobalis** [comment] 2021-06-04 16:59
Duplicate of #5388

**Closed by nabobalis** 2021-06-04 16:59 UTC
Labels: Effort Low, Feature Request, Priority Low, map
