### ISSUE TITLE
Alignment of Halpha & HMI composite maps

### ISSUE THREAD

**Issue by slyardley** [sunpy/sunpy#1615] opened 2015-11-20 14:32 UTC
I am trying to create a composite map consisting of submaps of H-alpha and HMI data. The H-alpha data seems to be offset in both the x and y direction by ~100", compared with HMI.

Halpha fits: 
ftp://ftp.kso.ac.at/Ha4M/2011/20110605/processed/kanz_halph_fi_20110605_065522.fts
(password for Halpha available here: http://cesar.kso.ac.at/main/ftp.php)

HMI fits: 
http://jsoc.stanford.edu/SUM72/D761559934/S00000/
(hmi.M_720s.20110605_070000_TAI.1.magnetogram.fits)

``` python
hmap = sunpy.map.Map('kanz_halph_fi_20110605_065522.fts').rotate()
hmap.meta['waveunit'] = 'AA' #changing ANG to proper units
hmap.meta['CTYPE1'] = 'HPLN-TAN'
hmap.meta['CTYPE2'] = 'HPLT-TAN'
smap = hmap.submap(u.Quantity([-100, 500], u.arcsec),
                   u.Quantity([-600, -250], u.arcsec))
hmimap = sunpy.map.Map('hmi.M_720s.20110605_070000_TAI.1.magnetogram.fits').rotate()
shmimap = hmimap.submap(u.Quantity([-100, 500], u.arcsec),
                   u.Quantity([-600, -250], u.arcsec))

comp_map = sunpy.map.Map(smap,shmimap, composite=True)
comp_map.set_alpha(1, 0.75)
comp_map.set_colors(1,'winter')
comp_map.set_levels(1, [-300,-500,300,500])
fig = plt.figure(figsize=(12,8))
comp_map.plot()
plt.title('2011-06-05 06:55:22')

```

![comp_plot](https://cloud.githubusercontent.com/assets/5773943/11302049/e31dd534-8f92-11e5-819f-30ac8e586830.png)

**Comment by Cadair** [comment] 2015-11-20 14:36
The alignment between the two images is only as good as the respective pointing information in the HMI and H alpha headers. I would assume the H aplha header is not accurate?

**Comment by slyardley** [comment] 2015-11-20 15:28
I couldn't see anything in the headers (unless I missed it). Also I have made the same plot before in IDL with no alignment issues?

**Comment by Cadair** [comment] 2015-11-20 15:41
@slyardley interesting. I will try and take a look over the weekend, but I have limited ideas and all the ones I do have are scary. Have you used these two exact files in IDL?

**Comment by slyardley** [comment] 2015-11-20 16:04
Halpha is the same file, HMI is a different file. Although, I have just found the original HMI file to recreate the IDL plot and it still gives the same result.

**Comment by Cadair** [comment] 2015-11-20 16:06
A sticky one! Could be fun!

**Comment by wafels** [comment] 2015-11-20 16:13
Would you be willing to share your IDL code?

Coincidentally, I am trying to overplot HMI and Coimbra spectroheliograph
data, and I too am coming across alignment issues.  I have tried the
overplot using sunpy/master only.  I have not tried the overplot in IDL
yet.  Thanks!

**Comment by slyardley** [comment] 2015-11-20 16:35
Here's the idl code I have used to make the same figure:

```IDL

fits2map, 'kanz_halph_fi_20110605_065522.fts', map

loadct,3
set_plot, 'ps',/copy
device,filename='Halpha_over.ps',/color
plot_map, map, xr=[-150,500],yr=[-250,-600], title='Kanzelh!X!Z(00F6)he Observatory 5-Jun-2011 06:55:22 UT'
loadct,0
set_line_color
plot_map, rmap,/over,/positive,color=1, levels=500
plot_map, rmap,/over,/negative,color=0, levels=-500

arrow,400,-350, 350,-400,/data, thick=2.5, color=1
arrow,375,-270, 325,-320,/data, thick=2.5, color=1
arrow,90,-320, 140,-370,/data, thick=2.5, color=1

device,/close
```


(The hmi map - rmap has come from a .sav file but is just the usual HMI fits file that has been converted to a map structure after the application aia_prep)

**Comment by larrymanley** [comment] 2015-11-20 18:17
Although you are taking a sub-map, could plate scale be an issue?
Solarsoft's aia_prep changes HMI's plate scale from ~0.5 to 0.6, while an
HMI map in Sunpy will remain at 0.5 with a not-quite-zero rotation.

**Comment by Cadair** [comment] 2015-11-22 21:57
@larrymanley in theory it shoudn't as it should be plotting in physical coordinates at two different plate scales. It's worth a look though.

**Comment by Cadair** [comment] 2016-02-05 14:38
@slyardley @wafels Did you ever make any headway with this?

**Comment by wafels** [comment] 2016-02-05 14:44
sorry - I have not followed this up.

**Comment by slyardley** [comment] 2016-02-05 14:50
Neither have I although, I’m working on another project now that might require this so might look into it again soon.


On 5 Feb 2016, at 14:44, wafels <notifications@github.com<mailto:notifications@github.com>> wrote:

sorry - I have not followed this up.

On Fri, Feb 5, 2016 at 9:38 AM, Stuart Mumford <notifications@github.com<mailto:notifications@github.com>>
wrote:

> @slyardley <https://github.com/slyardley> @wafels
> <https://github.com/wafels> Did you ever make any headway with this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sunpy/sunpy/issues/1615#issuecomment-180383032>.
>

—
Reply to this email directly or view it on GitHub<https://github.com/sunpy/sunpy/issues/1615#issuecomment-180384474>.

--

Stephanie Yardley, PhD Student,
Mullard Space Science Laboratory,
Holmbury St. Mary,
Dorking,
Surrey, RH5 6NT

stephanie.yardley.13@ucl.ac.uk<mailto:stephanie.yardley.13@ucl.ac.uk>
Tel: +44(0)1483 204 932

**Comment by ayshih** [comment] 2019-05-23 18:58
I suspect that #3057 and #2224 are the issue here

**Comment by ayshih** [comment] 2019-05-23 19:01
Or, I guess, #2630.  I haven't yet tried to reproduce this issue

**Comment by ayshih** [comment] 2019-10-16 13:37
I've finally looked into this.  The small inaccuracy in HMI observer location is not the main problem here.  Instead, the problem is that the Kanzelhoehe H-alpha map does not use a standard FITS keyword (e.g., `CROTA2`) to specify the rotation angle.  Instead, it appears to use `ANGLE`, with a sense that is opposite of the standard direction of `CROTA2`.  I guess SSW supports this keyword, but SunPy does not (at least not currently).

Replace:
```python
hmap = sunpy.map.Map('kanz_halph_fi_20110605_065522.fts').rotate()
```
with
```python
hmap = sunpy.map.Map('kanz_halph_fi_20110605_065522.fts')
hmap.meta['crota2'] = -hmap.meta['angle']  # note the negative sign
hmap = hmap.rotate()
```

(Be aware that some of the code snippets in this thread, particularly the submap call, needs to be modified to work on the current version of SunPy.)

@wafels will have to comment on whether he ever resolved his related issue with the Coimbra spectroheliograph data.

**Comment by wtbarnes** [comment] 2020-01-22 06:58
I'm going to close this as this is ultimately an issue with the Halpha header and @ayshih has provided a solution. @wafels if the Coimbra issue still persists, we should open a separate issue

**Closed by wtbarnes** 2020-01-22 06:58 UTC
Labels: Bug(?), Close?, map
