### ISSUE TITLE
AttributeError: module 'contextlib' has no attribute 'asynccontextmanager' in conda build

### ISSUE THREAD

**Issue by agy-why** [sunpy/sunpy#4608] opened 2020-10-28 09:47 UTC
Dear sunpy developer,

I am trying to use sunpy `2.0.3` the build from `conda` in a `jupyter notebook`.

```python
import sunpy
```
works but 
```python
import sunpy.map
```

returns:
```
AttributeError: module 'contextlib' has no attribute 'asynccontextmanager'
```

Is there a workaround?

I thank you in advance,

Yori Fournier

**Comment by nabobalis** [comment] 2020-10-28 09:55
Could you post more of the error log please?

**Comment by agy-why** [comment] 2020-10-28 10:09
Sure
```
from sunpy.map import Map
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-c3b5315cc07a> in <module>
----> 1 from sunpy.map import Map

/projects/anaconda38/envs/py36new/lib/python3.6/site-packages/sunpy/map/__init__.py in <module>
      6 from sunpy.map.mapbase import GenericMap
      7 
----> 8 from sunpy.map import sources
      9 from sunpy.map.header_helper import *
     10 from sunpy.map.map_factory import Map
/projects/anaconda38/envs/py36new/lib/python3.6/site-packages/sunpy/map/sources/__init__.py in <module>
     10            'source_stretch']
     11 
---> 12 from ..map_factory import Map
     13 from .hinode import SOTMap, XRTMap
     14 from .iris import SJIMap
/projects/anaconda38/envs/py36new/lib/python3.6/site-packages/sunpy/map/map_factory.py in <module>
     12 
     13 from sunpy import log
---> 14 from sunpy.data import cache
     15 from sunpy.io.file_tools import read_file
     16 from sunpy.io.header import FileHeader
/projects/anaconda38/envs/py36new/lib/python3.6/site-packages/sunpy/data/__init__.py in <module>
      3 import sunpy
      4 from sunpy import config
----> 5 from sunpy.data._sample import download_sample_data
      6 from sunpy.data.data_manager.cache import Cache
      7 from sunpy.data.data_manager.downloader import ParfiveDownloader
/projects/anaconda38/envs/py36new/lib/python3.6/site-packages/sunpy/data/_sample.py in <module>
      5 from sunpy import log
      6 from sunpy.util.config import _is_writable_dir, get_and_create_sample_dir
----> 7 from sunpy.util.parfive_helpers import Downloader
      8 
      9 _BASE_URLS = (
/projects/anaconda38/envs/py36new/lib/python3.6/site-packages/sunpy/util/parfive_helpers.py in <module>
      3 
      4 import aiohttp
----> 5 import parfive
      6 from parfive import Results
      7 
/projects/anaconda38/envs/py36new/lib/python3.6/site-packages/parfive/__init__.py in <module>
      3 from pkg_resources import get_distribution, DistributionNotFound
      4 
----> 5 from .downloader import Downloader
      6 from .results import Results
      7 
/projects/anaconda38/envs/py36new/lib/python3.6/site-packages/parfive/downloader.py in <module>
     15 
     16 try:
---> 17     import aioftp
     18 except ImportError:
     19     aioftp = None
/projects/anaconda38/envs/py36new/lib/python3.6/site-packages/aioftp/__init__.py in <module>
      2 # flake8: noqa
      3 
----> 4 from .client import *
      5 from .common import *
      6 from .errors import *
/projects/anaconda38/envs/py36new/lib/python3.6/site-packages/aioftp/client.py in <module>
    551 
    552 
--> 553 class Client(BaseClient):
    554     """
    555     FTP client.
/projects/anaconda38/envs/py36new/lib/python3.6/site-packages/aioftp/client.py in Client()
   1162 
   1163     @classmethod
-> 1164     @contextlib.asynccontextmanager
   1165     async def context(cls, host, port=DEFAULT_PORT, user=DEFAULT_USER,
   1166                       password=DEFAULT_PASSWORD, account=DEFAULT_ACCOUNT,
AttributeError: module 'contextlib' has no attribute 'asynccontextmanager'
```

**Comment by agy-why** [comment] 2020-10-28 10:10
That is all I have. do you need anything else? env? setup...

**Comment by nabobalis** [comment] 2020-10-28 10:18
So the issue is that somehow the version of "aioftp" that was installed by conda does not work for python 3.6. 

Can you tell me what version is installed? It should be "0.16.1". (There might be an issue with the parfive conda recipe).

**Comment by agy-why** [comment] 2020-10-29 10:31
Good morning, 

Thank you for your fast comments.

we could solve the problem by installing per hand (with pip) the correct version but per default the 0.17.x was installed, so indeed it could be that the recipe has an issue?

I wish you a nice day,

Yori

**Comment by nabobalis** [comment] 2020-10-29 10:34
Thanks for this, I have raised the issue upstream so hopefully this will be fixed over the next few days.

**Comment by agy-why** [comment] 2020-10-29 10:36
Thank you very much, I wish you a nice day.

**Comment by nabobalis** [comment] 2020-10-29 10:38
I am going to reopen this so we remember to fix this!

**Comment by nabobalis** [comment] 2020-10-29 10:57
Sorry @agy-why, can you also tell me the parfive version that was installed?

**Comment by dstansby** [comment] 2020-10-29 15:07
@nabobalis can you post a link to the upstream issue you reported?

**Comment by nabobalis** [comment] 2020-10-29 15:09
> @nabobalis can you post a link to the upstream issue you reported?

It was to stuart personally and it might be a bug in the conda resolver.

**Comment by nabobalis** [comment] 2020-10-29 15:48
Installing parfive under 3.6 resolves fine but as soon as you do the full install with sunpy, it pulls the wrong version of aioftp.

**Comment by agy-why** [comment] 2020-10-29 15:50
version of parfive is 1.0.2

**Comment by dstansby** [comment] 2020-11-20 12:31
I think this is an upstream `aiohttp` bug, since trying to install `aiohttp` on a clean conda python 3.6 install will try and install the python 3.7 version:

```bash
$ conda install -c conda-forge aiohttp
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/dstansby/miniconda3/envs/py36

  added / updated specs:
    - aiohttp


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    aiohttp-3.7.3              |   py36h7b4949f_0         598 KB  conda-forge
    async-timeout-3.0.1        |          py_1000          11 KB  conda-forge
    attrs-20.3.0               |     pyhd3deb0d_0          41 KB  conda-forge
    certifi-2020.11.8          |   py36h79c6626_0         150 KB  conda-forge
    chardet-3.0.4              |py36h2432673_1008         193 KB  conda-forge
    idna-2.10                  |     pyh9f0ad1d_0          52 KB  conda-forge
    idna_ssl-1.1.0             |py36h9f0ad1d_1001           7 KB  conda-forge
    multidict-4.7.5            |   py36h9de38fb_2          60 KB  conda-forge
    openssl-1.1.1h             |       haf1e3a3_0         1.9 MB  conda-forge
    python_abi-3.6             |          1_cp36m           4 KB  conda-forge
    typing-extensions-3.7.4.3  |                0           8 KB  conda-forge
    typing_extensions-3.7.4.3  |             py_0          25 KB  conda-forge
    yarl-1.6.3                 |   py36h6941dd6_0         132 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         3.1 MB

The following NEW packages will be INSTALLED:

  aiohttp            conda-forge/osx-64::aiohttp-3.7.3-py36h7b4949f_0
  async-timeout      conda-forge/noarch::async-timeout-3.0.1-py_1000
  attrs              conda-forge/noarch::attrs-20.3.0-pyhd3deb0d_0
  chardet            conda-forge/osx-64::chardet-3.0.4-py36h2432673_1008
  idna               conda-forge/noarch::idna-2.10-pyh9f0ad1d_0
  idna_ssl           conda-forge/osx-64::idna_ssl-1.1.0-py36h9f0ad1d_1001
  multidict          conda-forge/osx-64::multidict-4.7.5-py36h9de38fb_2
  python_abi         conda-forge/osx-64::python_abi-3.6-1_cp36m
  typing-extensions  conda-forge/noarch::typing-extensions-3.7.4.3-0
  typing_extensions  conda-forge/noarch::typing_extensions-3.7.4.3-py_0
  yarl               conda-forge/osx-64::yarl-1.6.3-py36h6941dd6_0

The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2020.10.14~ --> conda-forge::ca-certificates-2020.11.8-h033912b_0
  certifi            pkgs/main/noarch::certifi-2020.6.20-p~ --> conda-forge/osx-64::certifi-2020.11.8-py36h79c6626_0

The following packages will be SUPERSEDED by a higher-priority channel:

  openssl                                         pkgs/main --> conda-forge


Proceed ([y]/n)? n


CondaSystemExit: Exiting.
```

**Comment by dstansby** [comment] 2020-11-20 12:33
I think this is an upstream `aioftp` bug, as trying to install aioftp in a clean conda python 3.6 install tries to install a version not compatible with python 3.6:

```bash
$ conda install -c conda-forge aioftp
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/dstansby/miniconda3/envs/py36

  added / updated specs:
    - aioftp


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2020.11.8          |   py36h79c6626_0         150 KB  conda-forge
    openssl-1.1.1h             |       haf1e3a3_0         1.9 MB  conda-forge
    python_abi-3.6             |          1_cp36m           4 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         2.0 MB

The following NEW packages will be INSTALLED:

  aioftp             conda-forge/noarch::aioftp-0.17.2-py_0
  python_abi         conda-forge/osx-64::python_abi-3.6-1_cp36m

The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2020.10.14~ --> conda-forge::ca-certificates-2020.11.8-h033912b_0
  certifi            pkgs/main/noarch::certifi-2020.6.20-p~ --> conda-forge/osx-64::certifi-2020.11.8-py36h79c6626_0

The following packages will be SUPERSEDED by a higher-priority channel:

  openssl                                         pkgs/main --> conda-forge
```

**Comment by nabobalis** [comment] 2020-11-20 12:35
I forgot about this completely.

**Comment by dstansby** [comment] 2020-11-20 12:36
Oh look here's an issue someone opened earlier: https://github.com/conda-forge/aioftp-feedstock/issues/10

**Comment by nabobalis** [comment] 2020-11-20 13:44
A fix upstream is in progress. I am unclear how long it will take.

**Comment by dstansby** [comment] 2020-11-20 23:06
Since https://github.com/conda-forge/sunpy-feedstock/pull/80 was merged, this is no longer an issue for sunpy. Doing `conda install sunpy` will install a working version of `aioftp` on python 3.6. If you have already installed sunpy, running `conda install 'aioftp<0.17'` should fix the issue.

Since there are upstream bugs open for the upstream issue, and it's fixed for us, I'm going to close this. Thanks for reporting it!

**Closed by dstansby** 2020-11-20 23:06 UTC
Labels: Bug(?), Effort Low, Infrastructure, Package Novice, Priority High, Upstream Fix Required, net
