### ISSUE TITLE
Increase visibility of differential rotation code in docs

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2864] opened 2018-12-10 17:45 UTC
We had a report of people not knowing we had it.

**Comment by Cadair** [comment] 2018-12-12 17:43
I am not entirely sure how we would go about doing this, it's very easy to search for and only one click into `sunpy.physics` away to the API docs. Maybe adding it to the user guide?

**Comment by wtbarnes** [comment] 2018-12-12 17:44
Duplicate of #2565

**Comment by wtbarnes** [comment] 2018-12-12 17:48
See also #2600

**Comment by nabobalis** [comment] 2020-07-11 20:53
Closed in favour of #2565

**Closed by nabobalis** 2020-07-11 20:53 UTC
Labels: Documentation, physics
