### ISSUE TITLE
Stereoscopic 3D example regularly failing during doc build

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#7278] opened 2023-10-31 10:14 UTC
### Describe the bug

The stereoscopic 3D example is regularly failing during the online doc build with:

```python

/home/runner/work/sunpy/sunpy/examples/showcase/stereoscopic_3d.py failed leaving traceback:
    gallery_conf["filename_pattern"] = '^((?!skip_).)*$'
Traceback (most recent call last):
    gallery_conf["ignore_pattern"]   = '__init__\\.py'
  File "/home/runner/work/sunpy/sunpy/examples/showcase/stereoscopic_3d.py", line 35, in <module>

    aia_map = sunpy.map.Map(aia_file)
  File "/home/runner/work/sunpy/sunpy/.tox/build_docs-gallery/lib/python3.9/site-packages/astropy/utils/decorators.py", line 604, in wrapper
    return function(*args, **kwargs)
  File "/home/runner/work/sunpy/sunpy/.tox/build_docs-gallery/lib/python3.9/site-packages/sunpy/map/map_factory.py", line 288, in __call__
Error:     raise RuntimeError('No maps loaded')
RuntimeError: No maps loaded
```

We should replace the data with other data that doesn't fail to download all the time.

### To Reproduce

import sunpy

sunpy.map.Map(...)
etc

**Comment by ayshih** [comment] 2023-10-31 13:01
While the downloading for that example has failed a bunch recently, it also succeeded for all of the CI and RTD builds on the PRs I updated last night, so I'd chalk this up to data-provider flakiness rather than "consistently failing".

**Comment by ayshih** [comment] 2023-10-31 16:01
This gallery example has succeeded today on three more build sets, so I'm closing this issue

**Comment by dstansby** [comment] 2023-11-05 21:50
It failed again today: https://github.com/sunpy/sunpy/actions/runs/6759841345/job/18373089783. I'm going to re-open this, as I think it's failing enough to be annoying and for us to try and find a better solution. I've changed "consistently" to "regularly" in the title and description though.

**Comment by ayshih** [comment] 2023-11-06 04:11
\<shrug\>  If the example continues to use a true stereoscopic observation, it has to include EUVI, so pretty much the only option is to replace AIA with SUVI.  Or to separately host the data files.

I'll note that if these example failures are always because the AIA data is failing to download, the problem isn't really with this example in any way – because it's not like the file should be any more difficult to download than any other file – but more likely that our scheduled CI builds have enough JSOC downloads that we're getting put into JSOC jail.  That is, "fixing" this example doesn't fix the underlying issue.

**Comment by dstansby** [comment] 2023-11-06 08:52
How about adding the files to the sample data and avoiding JSOC altogether?

**Closed** 2023-11-15 05:49 UTC
Labels: Bug, Documentation, Priority High
