### ISSUE TITLE
Class methods not in documentation

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#2348] opened 2017-11-22 21:17 UTC
e.g. http://docs.sunpy.org/en/stable/api/sunpy.net.fido_factory.UnifiedResponse.html doesn't contain documentation for the class methods of `UnifiedResponse`.

**Comment by dstansby** [comment] 2017-11-22 21:23
Another example which I guess is the same problem: I can't find any API docs for `draw_limb`: http://docs.sunpy.org/en/stable/search.html?q=draw_limb

**Comment by dstansby** [comment] 2017-11-25 20:05
After lots of digging, this seems to be a one-off problem with `UnifiedResponse`, and I have no idea why. The automatically generated `.rst` file is missing it's method documentation:

```rst
UnifiedResponse
===============

.. currentmodule:: sunpy.net.fido_factory

.. autoclass:: UnifiedResponse
   :show-inheritance:
```
but it should look like the `UnifiedDownloaderFactory` generated file:
```rst
UnifiedDownloaderFactory
========================

.. currentmodule:: sunpy.net.fido_factory

.. autoclass:: UnifiedDownloaderFactory
   :show-inheritance:

   .. rubric:: Methods Summary

   .. autosummary::

      ~UnifiedDownloaderFactory.__call__
      ~UnifiedDownloaderFactory.fetch
      ~UnifiedDownloaderFactory.search

   .. rubric:: Methods Documentation

   .. automethod:: __call__
   .. automethod:: fetch
   .. automethod:: search
```

**Comment by nabobalis** [comment] 2018-03-27 12:40
We have a method summary on there?

**Comment by nabobalis** [comment] 2018-04-18 10:58
Does the current stable version look the way it should?

**Comment by dstansby** [comment] 2018-04-18 11:14
I'm going to guess that it's fixed, since there are some methods documented in the current stable version

**Comment by nabobalis** [comment] 2018-04-18 11:34
It isn't fixed. It just seems to work on stable.

**Comment by Cadair** [comment] 2018-05-18 12:50
This appears to be a bug in automodapi, as it has been independently reported in the astropy [pkg-infrastructure channel](https://view.matrix.org/room/!pSKzsvYeCMfoKeaeZc:matrix.org/?anchor=$15265904153338aeJpl:openastronomy.org) If someone has time can they write up a minimal example and report it on automodapi?!

**Comment by jairideout** [comment] 2018-10-31 22:06
I found the issue in automodapi (https://github.com/astropy/sphinx-automodapi/issues/52) and submitted a PR with a minimal reproducible example and a potential fix (https://github.com/astropy/sphinx-automodapi/pull/53).

The issue is that `automodsumm` uses `__slots__` to define class members if the `__slots__` attribute exists, and any class derived from the `abc` or `collections.abc` modules will have an empty `__slots__` attribute. Since `sunpy.net.fido_factory.UnifiedResponse` is derived from `collections.abc.Sequence`, its members aren't being listed due to this bug.

**Comment by jairideout** [comment] 2018-11-02 16:48
The issue has been fixed in sphinx-automodapi (https://github.com/astropy/sphinx-automodapi/pull/53). I confirmed that the docs build correctly for `UnifiedResponse` (and any other classes deriving from an ABC) using the latest `master` branch of sphinx-automodapi.

I think this issue can be closed once sphinx-automodapi has a new release. Alternatively, could sunpy's doc requirements be updated to use the development version of sphinx-automodapi? (`pip install git+https://github.com/astropy/sphinx-automodapi`).

Here's what the docs look like now:

<img width="393" alt="screen shot 2018-11-02 at 9 44 02 am" src="https://user-images.githubusercontent.com/1847232/47928553-e773ad00-de83-11e8-9870-444ac97e6828.png">

**Comment by Cadair** [comment] 2018-11-07 10:43
Thanks so much for fixing that @jairideout ! That's awesome. I will ask if astropy can bake a release for us :smile:

**Comment by nabobalis** [comment] 2018-11-10 09:53
Just checked on latest doc build. Those members are now there! 
So they should appear for stable once I trigger a rebuild as well. 

Thanks again @jairideout

**Closed by nabobalis** 2018-11-10 09:53 UTC
Labels: Affects Dev, Affects Release, Bug(?), Documentation, Upstream Fix Required

**Comment by Cadair** [comment] 2018-11-10 10:29
🎉🎉 thanks! @jairideout

**Comment by jairideout** [comment] 2018-11-12 17:12
@nabobalis @Cadair, no problem! Thanks for following up about the fix working with the latest doc build.
