### ISSUE TITLE
Add a test for the rotation of rectangularly pixelated data in Map

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#2721] opened 2018-08-13 20:31 UTC
This method

_https://github.com/sunpy/sunpy/blob/master/sunpy/map/mapbase.py#L716_

looks like it is trying to account for rectangular pixels.  If so, then the map test suite does not test rotation for when the map has rectangular pixels.

**Comment by Cadair** [comment] 2018-08-13 22:37
Yes, that method is coded to account for rectangular pixels. We should indeed test it.

**Comment by dstansby** [comment] 2020-04-08 16:31
This is now pointing to a random line in `mapbase.py` - which method is it that needs the extra testing?

**Comment by samriddhi-dev** [comment] 2021-05-03 12:32
Hi! Can I solve this?

**Comment by nabobalis** [comment] 2021-05-03 12:45
If you can figure out the function that needs testing.

**Comment by samriddhi-dev** [comment] 2021-05-03 12:47
Thanks!

**Comment by dstansby** [comment] 2021-05-03 19:29
```python
import matplotlib.pyplot as plt

import astropy.units as u
import numpy as np

import sunpy.data.sample as sample_data
import sunpy.map

aia_map = sunpy.map.Map(sample_data.AIA_193_IMAGE)
rect_map = aia_map.superpixel([2, 1] * u.pix, func=np.mean)
rect_rot_map = rect_map.rotate(30 * u.deg)
rect_rot_map.peek()
```

![Figure_1](https://user-images.githubusercontent.com/6197628/116923103-1e41fe00-ac4e-11eb-8407-85dd64f8f8fb.png)

suggests that it is working as intended, at least when the (0, 0) coordinate is in the center of the map. Adding this code snippet as a figure test would be good enough to close this issue I think.

**Comment by samriddhi-dev** [comment] 2021-05-05 14:00
I am working on this... can you give me 3-5 days time to submit it?

**Comment by samriddhi-dev** [comment] 2021-05-10 09:36
I am working on adding the hash. Then I will commit it.

**Comment by samriddhi-dev** [comment] 2021-05-10 12:38
I have done a PR.

**Comment by samriddhi-dev** [comment] 2021-05-12 13:30
Sure! @nabobalis

**Comment by samriddhi-dev** [comment] 2021-05-12 13:39
the hash was generated using py39, could that be the issue?

**Comment by nabobalis** [comment] 2021-05-12 13:40
It shouldn't be, this should also be on the pull request itself and not the issue.

**Closed** 2021-09-24 10:54 UTC
Labels: Tests, Package Novice, map, Priority Low, Effort Medium, Hacktoberfest, Good First Issue
