### ISSUE TITLE
HEK properties to return astropy quantities

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#1792] opened 2016-05-22 09:53 UTC
Would be nice to have the properties of HEK results be returned as astropy quantities, etc., for the same reasons we use quantities everywhere else.  "Quantifying" the required HEK properties would be a good start.

http://www.lmsal.com/hek/VOEvent_Spec.html

**Comment by abit2** [comment] 2017-01-13 19:10
@Cadair @wafels I would like to work on it 
Can you please elaborate on this

**Comment by wafels** [comment] 2017-01-13 20:19
Ankit,

All events stored by the HEK have a number of required properties.  These
are indicated by the red "req" table entry in the table on this web page:

http://www.lmsal.com/hek/VOEvent_Spec.html
At the moment, sunpy's hek module returns almost everything as a string,
even although the entries are not intended to be strings.  Results from the
HEK would be easier to use if they were parsed and converted to more fully
represent the descriptions given in the event specification above.  For
example, event start and end times should be represented in sunpy's time
format.  Event co-ordinates and bounding boxes should be returned as sunpy
co-ordinates.  So this feature request will require string parsing and
understanding what the HEK intended to be stored, exception handling, etc.

One way forward might be to define a generic feature/event object and then
create an HEK subclass.  This is because the HEK is not the only
feature/event catalog out there.  The HEK subclass could would be
responsible for understanding the feature/event properties that are common
to all HEK entries.

Thanks,

Jack

**Comment by abit2** [comment] 2017-01-15 17:17
@wafels
From what I could understand i was thinking of adding more getter functions in https://github.com/sunpy/sunpy/blob/master/sunpy/net/hek/hek.py#L103 should I go ahead with it

**Comment by abit2** [comment] 2017-01-16 09:01
@wafels can you explain a bit more on making a HEK subclass

**Comment by abit2** [comment] 2017-01-18 06:22
@wafels
i'm doing something like this http://pastebin.com/PVMjSdpL

**Comment by wafels** [comment] 2017-01-18 15:32
@ankit - thinking about it a bit more, I think making an HEK subclass of a
more general event class is not what this feature request is about.  That
is somewhat more difficult task.  Also, given that the HEK and HELIO
feature/event catalogs store information in different ways, there is likely
always going to be the need to be able to understand how a given
feature/event property is represented by each catalog.  Therefore, the
original goal of returning HEK properties as astropy quantities is
paramount for this feature request.

This line

*https://github.com/sunpy/sunpy/blob/master/sunpy/net/hek/hek.py#L144
<https://github.com/sunpy/sunpy/blob/master/sunpy/net/hek/hek.py#L144>*

converts the XML response of the HEK to a dictionary.  One could check the
dictionary for the presence of a key and then attempt to parse the value
according to how it should be stored.  So maybe the line should read

* return parse_hek_response_to_quantities(xml_to_dict(response))*

with the function *parse_hek_response_to_quantities *describing how each
dictionary key-value pair be handled.  This approach minimizes changes to
the existing code base and keeps a bunch of parsing/exception handling code
in a separate place.

What do you think?

Thanks,

Jack

**Comment by abit2** [comment] 2017-01-20 10:19
@wafels sounds good

**Comment by wafels** [comment] 2017-01-20 19:35
Ankit,

I translated the table on *http://www.lmsal.com/hek/VOEvent_Spec.html
<http://www.lmsal.com/hek/VOEvent_Spec.html>* to an Excel spreadsheet.

*https://www.dropbox.com/s/ouckf26snkub8xr/hek-better.xlsx?dl=0
<https://www.dropbox.com/s/ouckf26snkub8xr/hek-better.xlsx?dl=0>*

It can be read in to a pandas dataframe quite easily

*import pandas as pd*
*df = pd.read_excel(file_path, index_col=0).dropna()*

and interrogated from there.  For example, to get the required parameters
for flares:

*required_parameters = [s.lower() for s in df[df['FL'] ==
'req'].index.tolist()]*

The 'Type' column gives hints (at least in some cases) as to how the data
should appear in a sunpy session.  However, I think many properties will
need additional parsing in order to fully understand them.  I think working
on the required parameters for each feature/event type would be a great
start, with parsing for other optional properties to come later.

Thanks,

Jack

**Comment by vermashresth** [comment] 2018-03-10 13:41
Hi! @wafels 
The PR for this issue seems to have been abandoned, so if it is still relevant, I would like to make an attempt at this.
From what I understand from the discussion, we first have to use the csv file you extracted from [http://www.lmsal.com/hek/VOEvent_Spec.html](http://www.lmsal.com/hek/VOEvent_Spec.html) as a lookup table to generate a list of parameters that are `required` for the given event type. Then we have to parse them into their respective Object Type/Astropy Quantity.
One doubt, how do we determine what the specific type should be, for output? Because the type column in the table you provided is too generic, almost always gives `string` or `float` while we need more specific types like astropy quantities.

**Comment by wafels** [comment] 2018-03-10 16:17
You are right. Each of the HEK parameters will need an astropy quantity.  I can help you with determining which quantity is the correct one.  Parameters like bounding boxes will also need to be parsed and returned using the appropriate co-ordinate system.  I still think writing the function `parse_hek_response_to_quantities` is still the easiest way forward.  Returning quantities and co-ordinates will make the HEK parameters immediately more useful for everyone.

**Comment by wafels** [comment] 2018-03-10 16:18
And thanks for volunteering ti take on this PR!

**Comment by vermashresth** [comment] 2018-03-10 17:29
I have another doubt. I can't quite get it why we are parsing the output of `get_voevent()` function and not the actual content of `response` object. I'm sure I'm missing something there.
Also your code highlighting seems to be mismarked now because of changes over this time, I hope I'm not confused there.

**Comment by wafels** [comment] 2018-03-10 19:12
Yes, the line that I was referring to is no longer the same.

I'm not sure what you mean by 

> actual content of the response object

By default, the function `get_voevent()` already converts the `response` object from XML to a Python dictionary at the line `return xml_to_dict(response)`, because a Python dictionary is probably the more useful to the user than the response itself, which is an XML string.  A simple implementation solving #1792 is to parse the Python dictionary key-value pairs as required.  What do you have in mind instead?

**Comment by vermashresth** [comment] 2018-03-11 16:17
I meant that is there any specific reason that we apply parser on the python dictionary given by `get_voevent()` and not on the dictionaries(`Reponse` objects) inside list given by [search()](https://github.com/sunpy/sunpy/blob/master/sunpy/net/hek/hek.py#L94:L97) method of `HEKClient`? Because the parameter names that we get from the table you gave, they correspond more closely to the keys we get from response object rather than those we get in `voevent` (in names as well as in structure).

**Comment by souravghosh97** [comment] 2019-03-10 15:35
@wafels Is there any specific reason not to convert the ```result[0]['event_peaktime']``` to a time object?
like
```
>>> from sunpy.net import hek
>>> client = hek.HEKClient()  
>>> tstart = '2011/08/09 07:23:56'
>>> tend = '2011/08/09 12:40:29'
>>> event_type = 'FL'
>>> result = client.search(hek.attrs.Time(tstart,tend),hek.attrs.EventType(event_type))
>>> result[0]['event_peaktime']
'2011-08-09T11:55:00'
```
instead of ```'2011-08-09T11:55:00'``` should it be ```datetime.datetime(2011, 8, 9, 11, 55)```

**Comment by wafels** [comment] 2019-03-11 17:44
It should be a Time object.

**Comment by souravghosh97** [comment] 2019-03-11 19:59
@wafels 
```
>>> result[0]['hpc_bbox']
POLYGON((-470 -174,573 -174,573 476,-470 476,-470 -174))
```
what should be the sunpy object in this case

**Comment by wafels** [comment] 2019-03-12 02:19
This should return a SkyCoord object.  The polygon vertices are comma
separated.  The keyword "hpc_bbox" indicates that the polygon is a bounding
box and that the coordinates are specified in the helioprojective Cartesian
coordinate system.  The first coordinate is at -470'', -174''.  The second
coordinate is at 573'', -174'', and so on.  The observation time is the
value of *event_starttime*.  Unfortunately it looks like the observer
location is not recorded in the HEK result, so I would assume to just use
the location of the Earth.

You can return all the coordinates within a single SkyCoord object.

**Comment by souravghosh97** [comment] 2019-03-12 02:24
@wafels for heliographic_carrington what is the radius

**Comment by souravghosh97** [comment] 2019-03-19 08:01
```
from sunpy.net import hek
client = hek.HEKClient()  
tstart = '2011/08/09 07:23:56'
tend = '2011/08/09 12:40:29'
event_type = 'FL'
result = client.search(hek.attrs.Time(tstart,tend),hek.attrs.EventType(event_type))
print(result[7]['hpc_coord'])
print(result[7]['event_coordunit'])
```
The reult is  showing 
```
POINT(854.37 207.7254)
degrees
```


While converting hpc_coord to sunpy object i am getting this error
```
ValueError: Latitude angle(s) must be within -90 deg <= angle <= 90 deg, got 207.7254 deg
```

The event coord unit is degrees but latitude is beyonf 90

**Comment by jeffreypaul15** [comment] 2021-03-31 13:16
I'm assuming this a similar issue related to #5006 and PR #5131?

**Comment by nabobalis** [comment] 2021-03-31 13:23
Yes this is duplicate of #5006 but it has more info so I plan to leave this open.

**Comment by nabobalis** [comment] 2021-05-03 13:43
Superseded by #5006

**Closed by nabobalis** 2021-05-03 13:43 UTC
Labels: Effort Medium, Feature Request, Good First Issue, Hacktoberfest, Package Novice, Priority Medium, net
