### ISSUE TITLE
Installing a clean fork with docs dependencies does not succeed on Windows

### ISSUE THREAD

**Issue by Satan-Claws** [sunpy/sunpy#6808] opened 2023-02-28 03:44 UTC
Edit by @ayshih: As ultimately concluded, the issue is that installing a clean fork (specifically one that does not have knowledge of the tags of the main repo) with docs dependencies does not succeed on Windows.  This is because – as of this writing – we have a docs dependency of `sunkit-image` (cf. #6809), which itself requires `sunpy` of a minimum version.  Without tags, `sunpy` incorrectly reports its version as 0.1dev, so pip is unable to find a wheel of `sunkit-image` that is compatible with such a version of `sunpy`.

The reason why the failure was arcane in @Satan-Claws's case is that pip does not find wheel for `sunkit-image` 0.1 but did find the source, so pip tried to build the ancient `sunkit-image` 0.1 from source.  `sunkit-image` 0.1 pins `Cython` to the ancient 0.29.13.  And, `Cython` 0.29.13 fails to compile on Windows.  On other setups, the failure can instead be that pip would not find any compatible wheels for `sunkit-image`.

-----

### Describe the bug

Hello, I've been trying to make the environment for dev work on Windows and during sunkit's installation using `pip install -e .[dev]` it crashes. I've seen for fix here and there but nothing seems to work. I've changed `pip` ,`python`  and `setuptools` version multiple times but nothing has worked yet. `sunkit-image` installs normally in the environment but it doesn't with the `pip install -e .[dev]`. I do have Clang installed in this environment.

I've noticed it always crashes at the Cython part so I tried to install it independently and Cython did install. Running `pip install -e .[dev]` still gave a crash at cython. I looked at other bug fixes like these at AstroPy and other places as well. Seems like changing the version restriction on Cython or skipping Cython seems to work.

For reference:
https://github.com/cython/cython/issues/3941
https://github.com/astropy/specreduce/pull/78

I have a Linux Dual Boot so I'll try to setup my dev platform there and will update here.

### To Reproduce

$ cd sunpy-git
$ pip install -e .[dev]

### Screenshots

![image](https://user-images.githubusercontent.com/99952983/221746774-a9d9820a-cc80-4fa9-a616-5dfe2d479d01.png)

### System Details

- Python Version: 3.9.0, 3.9.10, 3.10.0, 3.11 (Checked on all)
- Pip Version 21.3.1, 23.0.1 

### Installation method

pip

**Comment by nabobalis** [comment] 2023-02-28 05:23
Right my bad. `sunpy` actually picked up a sunkit-image dependency a while back and my memory forgot that fact.

Why it won't just use the latest version of sunkit-image, I am unclear about. 

Can you do:

`pip install -e .`
Then if that works, do 
`pip install -e .[dev]`

**Comment by nabobalis** [comment] 2023-02-28 07:28
Can you also do a `pip freeze --all --no-input`, I want to see if I can replicate this. 

This could be a bug in setuptools_scm.

**Comment by Satan-Claws** [comment] 2023-02-28 07:53
>What does `git status` tell you?
On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        main

nothing added to commit but untracked files present (use "git add" to track)

> trying `pip install -e .`
It returns Successfully installed sunpy-4.1.dev971+g38857794c
> trying `pip install -e .[dev]
It too returned Successfully installed sunpy-4.1.dev971+g38857794c
> `pip freeze --all --no-input`
returned:
aioftp==0.21.4
aiohttp==3.8.4
aiosignal==1.3.1
alabaster==0.7.13
asdf==2.14.3
asdf-astropy==0.3.0
asdf-coordinates-schemas==0.1.0
asdf-standard==1.0.3
asdf-transform-schemas==0.3.0
asdf-unit-schemas==0.1.0
astropy==5.2.1
astropy-healpix==0.7
astroquery==0.4.6
async-timeout==4.0.2
attrs==22.2.0
Babel==2.11.0
beautifulsoup4==4.11.2
cachetools==5.3.0
cdflib==0.4.9
certifi==2022.12.7
chardet==5.1.0
charset-normalizer==3.0.1
click==8.1.3
click-default-group==1.2.2
cloudpickle==2.2.1
colorama==0.4.6
contourpy==1.0.7
coverage==7.2.1
cycler==0.11.0
Cython==0.29.33
dask==2023.2.1
distlib==0.3.6
docutils==0.19
drms==0.6.3
exceptiongroup==1.1.0
execnet==1.9.0
filelock==3.9.0
fonttools==4.38.0
frozenlist==1.3.3
fsspec==2023.1.0
Glymur==0.12.2
greenlet==2.0.2
h5netcdf==1.1.0
h5py==3.8.0
html5lib==1.1
hvpy==1.0.1
hypothesis==6.68.2
idna==3.4
imageio==2.26.0
imagesize==1.4.1
importlib-metadata==6.0.0
importlib-resources==5.12.0
incremental==22.10.0
iniconfig==2.0.0
isodate==0.6.1
jaraco.classes==3.2.3
Jinja2==3.1.2
jmespath==1.0.1
jplephem==2.18
jsonschema==4.17.3
keyring==23.13.1
kiwisolver==1.4.4
locket==1.0.0
lxml==4.9.2
MarkupSafe==2.1.2
matplotlib==3.7.0
more-itertools==9.1.0
mpl-animators==1.1.0
multidict==6.0.4
networkx==3.0
numpy==1.24.2
opencv-python==4.7.0.72
packaging==23.0
pandas==1.5.3
parfive==2.0.2
partd==1.3.0
Pillow==9.4.0
pip==23.0.1
platformdirs==3.0.0
pluggy==1.0.0
psutil==5.9.4
pydantic==1.10.5
pyerfa==2.0.0.1
Pygments==2.14.0
pyparsing==3.0.9
pyproject_api==1.5.0
pyrsistent==0.19.3
pytest==7.2.1
pytest-arraydiff==0.5.0
pytest-astropy==0.10.0
pytest-astropy-header==0.2.2
pytest-cov==4.0.0
pytest-doctestplus==0.12.1
pytest-filter-subpackage==0.1.2
pytest-mock==3.10.0
pytest-mpl==0.16.1
pytest-openfiles==0.5.0
pytest-remotedata==0.4.0
pytest-xdist==3.2.0
python-dateutil==2.8.2
pytz==2022.7.1
pyvo==1.4
PyWavelets==1.4.1
pywin32-ctypes==0.2.0
PyYAML==6.0
reproject==0.10.0
requests==2.28.2
requests-file==1.5.1
requests-toolbelt==0.10.1
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.7
scikit-image==0.19.3
scipy==1.10.1
semantic-version==2.10.0
setuptools==67.4.0
six==1.16.0
snowballstemmer==2.2.0
sortedcontainers==2.4.0
soupsieve==2.4
Sphinx==5.3.0
sphinx-automodapi==0.14.1
sphinx-bootstrap-theme==0.8.1
sphinx-changelog==1.2.0
sphinx-copybutton==0.5.1
sphinx-gallery==0.11.1
sphinx-hoverxref==1.3.0
sphinx_design==0.3.0
sphinxcontrib-applehelp==1.0.4
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
sphinxcontrib.jquery==3.0.0
sphinxext-opengraph==0.8.1
SQLAlchemy==2.0.4
sunkit-image==0.4.2
-e git+https://github.com/sunpy/sunpy@38857794c84a8a13d32d2e681582e9dcbf010144#egg=sunpy
sunpy-sphinx-theme==1.2.37
tifffile==2023.2.27
tomli==2.0.1
toolz==0.12.0
towncrier==22.8.0
tox==4.4.6
tqdm==4.64.1
typing_extensions==4.5.0
urllib3==1.26.14
virtualenv==20.19.0
webencodings==0.5.1
wheel==0.38.4
yarl==1.8.2
zeep==4.2.1
zipp==3.15.0




My Lectures are over, I'll create a new branch and will let you know if this occurs again.

**Comment by Satan-Claws** [comment] 2023-02-28 08:33
I created a completely new environment 
Got Clang 
Clone sunpy to a folder, in that root folder ran `pip install -e .` then ran `pip install -e .[dev]` then it showed "Successfully installed <a bunch of libraries that include sunkit-image-0.4.2>" and then I did `pip install -e .[docs]` (which I believe is a subset of [dev]?) and that terminated successfully too.

I am not quite sure if running `pip install -e .` before `pip install -e .[dev]` fixed it or not but there seems to be no error right now.

I'm trying to run `make html` ,will let you know if I have any errors

**Comment by nabobalis** [comment] 2023-02-28 16:35
So Albert found the problem last night:

The main problem is a clean fork has no git tags from the get go, so the build system is unable to get the version of sunpy and `pip` has to go through all of the dependencies and as a result pulls in a old package that lacks the correct metadata, has to build it and fails.

This was caused by the inclusion of sunkit-image which has a dependency on sunpy which means the entire thing is pretty circular. This will be changed later today.

The main fix for now is to sync the tags from here to your fork:

`git pull upstream --tags` assuming you have github.com/sunpy/sunpy configured as upstream

**Comment by Satan-Claws** [comment] 2023-02-28 17:02
I set up a new environment in WSL without any errors and I think I'll work in WSL this point on.

**Comment by nabobalis** [comment] 2023-02-28 21:09
We have a merged a fix for this, so this should not happen anymore. 

If you can update your fork, that should fix the issue.

**Comment by Satan-Claws** [comment] 2023-03-01 05:28
Alright, should I close this issue now?

**Closed** 2023-03-01 05:31 UTC
Labels: Bug, Infrastructure, Question
