### ISSUE TITLE
ImageAnimator axis_ranges bug

### ISSUE THREAD

**Issue by mbobra** [sunpy/sunpy#2617] opened 2018-05-03 19:56 UTC
The `ImageAnimator` [source code](https://github.com/sunpy/sunpy/blob/master/sunpy/visualization/imageanimator.py) says that the axis_ranges keyword can take one of two forms:

* It can have the same shape as the length of the data array along the dimension of any given axis, or
* It can have the same shape as the input data array.

However, the second form raises an error. 

Here are the inputs to the call:

```python
In [1]: print(data_cube.shape)
(16, 476, 1098)

In [2]: print(zmin, zmax)
0 16

In [3]: print(ymin, ymax)
0 476

In [4]: print(xdatacube.shape)
(16, 476, 1098)
```
Here is the call itself:

```python
outanimation = imageanimator.ImageAnimator(data_cube, axis_ranges=[(zmin, zmax), (ymin, ymax), xdatacube], cmap='seismic_r')
```

Here is the error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-8f91d9284783> in <module>()
      1 # errors:
----> 2 outanimation = imageanimator.ImageAnimator(data_cube, axis_ranges=[(zmin, zmax), (ymin, ymax), xdatacube], cmap='seismic_r')
      3 
      4 # works:
      5 # outanimation = imageanimator.ImageAnimator(data_cube, axis_ranges=[(zmin, zmax), (ymin, ymax), (xminasnan, xmax)], cmap='seismic_r')

~/sunpy/sunpy/visualization/imageanimator.py in __init__(self, data, image_axes, axis_ranges, **kwargs)
    647         # Run init for parent class
    648         super(ImageAnimator, self).__init__(data, image_axes=image_axes,
--> 649                                             axis_ranges=axis_ranges, **kwargs)
    650 
    651     def plot_start_image(self, ax):

~/sunpy/sunpy/visualization/imageanimator.py in __init__(self, data, image_axes, axis_ranges, **kwargs)
    475                        'slider_ranges': [self.axis_ranges[i] for i in self.slider_axes]}
    476         base_kwargs.update(kwargs)
--> 477         BaseFuncAnimator.__init__(self, data, **base_kwargs)
    478 
    479         # Undo hack of length 2 axis ranges

~/sunpy/sunpy/visualization/imageanimator.py in __init__(self, data, slider_functions, slider_ranges, fig, interval, colorbar, **kwargs)
    109 
    110         # Do Plot
--> 111         self.im = self.plot_start_image(self.axes)
    112 
    113         # Connect fig events

~/sunpy/sunpy/visualization/imageanimator.py in plot_start_image(self, ax)
    676             im = mpl.image.NonUniformImage(ax, **imshow_args)
    677             im.set_data(self.axis_ranges[self.image_axes[0]],
--> 678                         self.axis_ranges[self.image_axes[1]], data)
    679             ax.add_image(im)
    680             # Define the xlim and ylim bearing in mind that the pixel values along

~/anaconda/envs/sunpy-dev/lib/python3.6/site-packages/matplotlib/image.py in set_data(self, x, y, A)
    972         A = cbook.safe_masked_invalid(A, copy=True)
    973         if not (x.ndim == y.ndim == 1 and A.shape[0:2] == y.shape + x.shape):
--> 974             raise TypeError("Axes don't match array shape")
    975         if A.ndim not in [2, 3]:
    976             raise TypeError("Can only plot 2D or 3D data")

TypeError: Axes don't match array shape
```

**Comment by nabobalis** [comment] 2019-01-22 16:56
Will this be fixed by #2894?

**Comment by Cadair** [comment] 2019-01-23 11:09
@mbobra could you provide us a script to recreate this, so we can test if it is fixed by #2867 ? :)

**Comment by mbobra** [comment] 2019-01-24 00:49
@Cadair Yes! [Here you go](https://nbviewer.jupyter.org/github/mbobra/calculating-spaceweather-keywords/blob/master/movie_test_image_animator.ipynb).

**Comment by DanRyanIrish** [comment] 2019-03-13 15:41
As far as I can see, this issue was actually caused by poor and confusing documentation.  I don't think the way @mbobra defined the ```axis_ranges``` should have worked, but the documentation may have implied that it should have.

#2867 does not make ```ImageAnimator``` ```axis_ranges``` work as used in the above linked notebook.  It defines a new API that is less ambiguous and better documented.  So in this sense the issue is "fixed", but the animator calls in the notebook will have to be altered to not crash.

Hope this is helpful @mbobra!

**Closed** 2019-04-03 15:43 UTC
Labels: 0.9.x, Affects Release, Bug(?), visualization
