### ISSUE TITLE
aiaprep can not be used to align AIA and HMI images

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2747] opened 2018-09-11 14:29 UTC
`aiaprep` explicitly checks the type of the map to make sure it's `AIAMap` when really it should allow `HMIMap` as well because then you can align AIA images with HMI, and the metadata structure is sufficiently similar that there is no reason why this would not work.

The fix I think would be best would be to allow both `AIAMap` and `HMIMap` in [this](https://github.com/sunpy/sunpy/blob/master/sunpy/instr/aia.py#L45) `isinstance` check. On the other hand you could just drop it altogether and just hope it works :laughing:

**Comment by wtbarnes** [comment] 2018-09-11 17:02
Duplicate of #2331? Also see discussion in #1697.

**Comment by SolarDrew** [comment] 2018-09-11 17:07
Well-spotted. I think having one function rescale both AIA and HMI data is a good solution to both this and #2331 if the plate scale is the only difference, but we'll have to put in a check so that it uses the correct one.

**Comment by Cadair** [comment] 2018-09-12 10:32
if given a HMI map, aiaprep should change it's plate scale to 0.6. As that is how you would align it to the AIA data.

This is defiantly a dupe of #2331 though.

**Closed** 2018-09-12 14:39 UTC
Labels: Bug(?), Effort Low, Package Novice, Priority High, map
