### ISSUE TITLE
hgs_to_hcc(heliogcoord, heliocframe) : Convert from Heliographic Stonyhurst to Heliograpic Carrington.

### ISSUE THREAD

**Issue by gulshan-mittal** [sunpy/sunpy#2470] opened 2018-02-17 23:27 UTC
**Wrong Documentation** under SunpyCoordinates-> sunpy.coordinates.transformations Module.
It should be Convert from Heliographic Stonyhurst to Heliocentric .
**Link to documentation** : http://docs.sunpy.org/en/latest/code_ref/coordinates.html#module-sunpy.coordinates.transformations. @Cadair @nabobalis

**Comment by nabobalis** [comment] 2018-02-18 12:31
Sorry, I am not sure I see what the problem is.

**Comment by gulshan-mittal** [comment] 2018-02-18 13:06
@nabobalis 
![issue1](https://user-images.githubusercontent.com/28534390/36352124-4df56088-14da-11e8-94ed-08d9672270d5.png) In this conversion should be Heliographic Stonyhurst to Heliocentric instead of  Heliographic Stonyhurst to Heliograpic Carrington.

**Comment by nabobalis** [comment] 2018-02-18 13:28
Ah yes.  That should be changed.

**Comment by nabobalis** [comment] 2018-03-07 17:38
Fixed by #2502

**Closed by nabobalis** 2018-03-07 17:38 UTC
Labels: Documentation, coordinates
