### ISSUE TITLE
Sunpy no longer compatible with newest numpy

### ISSUE THREAD

**Issue by AlexPietrow** [sunpy/sunpy#6767] opened 2023-02-04 10:14 UTC
### Describe the bug

The newest numpy (1.24.1) does not seem to be compatible with sunpy anymore. Just importing a function gives an error. 

### To Reproduce
```python
In [2]: import sunpy.map
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[2], line 1
----> 1 import sunpy.map

File ~/.local/lib/python3.10/site-packages/sunpy/map/__init__.py:7
      1 """
      2 SunPy Map
      3 
      4 isort:skip_file
      5 """
      6 from ._units import maxwell
----> 7 from sunpy.map.mapbase import *
      9 from sunpy.map import sources
     10 from sunpy.map.header_helper import *

File ~/.local/lib/python3.10/site-packages/sunpy/map/mapbase.py:35
     32 from astropy.visualization.wcsaxes import Quadrangle, WCSAxes
     34 # The next two are not used but are called to register functions with external modules
---> 35 import sunpy.coordinates
     36 import sunpy.io as io
     37 import sunpy.io._fits

File ~/.local/lib/python3.10/site-packages/sunpy/coordinates/__init__.py:21
      1 """
      2 This subpackage contains:
      3 
   (...)
     18 
     19 """
---> 21 from . import sun
     22 from .ephemeris import *
     23 from .frames import *

File ~/.local/lib/python3.10/site-packages/sunpy/coordinates/sun.py:34
     32 from .ephemeris import get_earth
     33 from .frames import HeliographicStonyhurst
---> 34 from .transformations import _SOLAR_NORTH_POLE_HCRS, _SUN_DETILT_MATRIX
     36 __author__ = "Albert Y. Shih"
     37 __email__ = "ayshih@gmail.com"

File ~/.local/lib/python3.10/site-packages/sunpy/coordinates/transformations.py:647
    642 _SOLAR_NORTH_POLE_HCRS = UnitSphericalRepresentation(lon=constants.get('alpha_0'),
    643                                                      lat=constants.get('delta_0'))
    646 # Calculate the rotation matrix to de-tilt the Sun's rotation axis to be parallel to the Z axis
--> 647 _SUN_DETILT_MATRIX = _rotation_matrix_reprs_to_reprs(_SOLAR_NORTH_POLE_HCRS,
    648                                                      CartesianRepresentation(0, 0, 1))
    651 def _affine_params_hcrs_to_hgs(hcrs_time, hgs_time):
    652     """
    653     Return the affine parameters (matrix and offset) from HCRS to HGS
    654 
   (...)
    661     vector.
    662     """

File ~/.local/lib/python3.10/site-packages/sunpy/coordinates/transformations.py:597, in _rotation_matrix_reprs_to_reprs(start_representation, end_representation)
    595 A = start_representation.to_cartesian()
    596 B = end_representation.to_cartesian()
--> 597 rotation_axis = A.cross(B)
    598 rotation_angle = -np.arccos(A.dot(B) / (A.norm() * B.norm()))  # negation is required
    600 if rotation_angle.isscalar:
    601     # This line works around some input/output quirks of Astropy's rotation_matrix()

File ~/.local/lib/python3.10/site-packages/astropy/coordinates/representation.py:1513, in CartesianRepresentation.cross(self, other)
   1508     raise TypeError("cannot only take cross product with another "
   1509                     "representation, not a {} instance."
   1510                     .format(type(other))) from err
   1511 # erfa pxp: p-vector outer (=vector=cross) product.
   1512 sxo = erfa_ufunc.pxp(self.get_xyz(xyz_axis=-1),
-> 1513                      other_c.get_xyz(xyz_axis=-1))
   1514 return self.__class__(sxo, xyz_axis=-1)

File ~/.local/lib/python3.10/site-packages/astropy/coordinates/representation.py:1351, in CartesianRepresentation.get_xyz(self, xyz_axis)
   1346         return np.moveaxis(self._xyz, self._xyz_axis, xyz_axis)
   1348 # Create combined array.  TO DO: keep it in _xyz for repeated use?
   1349 # But then in-place changes have to cancel it. Likely best to
   1350 # also update components.
-> 1351 return np.stack([self._x, self._y, self._z], axis=xyz_axis)

File <__array_function__ internals>:200, in stack(*args, **kwargs)

File ~/.local/lib/python3.10/site-packages/astropy/units/quantity.py:1683, in Quantity.__array_function__(self, function, types, args, kwargs)
   1670 # A function should be in one of the following sets or dicts:
   1671 # 1. SUBCLASS_SAFE_FUNCTIONS (set), if the numpy implementation
   1672 #    supports Quantity; we pass on to ndarray.__array_function__.
   (...)
   1680 # function is in none of the above, we simply call the numpy
   1681 # implementation.
   1682 if function in SUBCLASS_SAFE_FUNCTIONS:
-> 1683     return super().__array_function__(function, types, args, kwargs)
   1685 elif function in FUNCTION_HELPERS:
   1686     function_helper = FUNCTION_HELPERS[function]

File /usr/lib64/python3.10/site-packages/numpy/core/shape_base.py:471, in stack(arrays, axis, out, dtype, casting)
    469 sl = (slice(None),) * axis + (_nx.newaxis,)
    470 expanded_arrays = [arr[sl] for arr in arrays]
--> 471 return _nx.concatenate(expanded_arrays, axis=axis, out=out,
    472                        dtype=dtype, casting=casting)

File <__array_function__ internals>:200, in concatenate(*args, **kwargs)

File ~/.local/lib/python3.10/site-packages/astropy/units/quantity.py:1688, in Quantity.__array_function__(self, function, types, args, kwargs)
   1686 function_helper = FUNCTION_HELPERS[function]
   1687 try:
-> 1688     args, kwargs, unit, out = function_helper(*args, **kwargs)
   1689 except NotImplementedError:
   1690     return self._not_implemented_or_raise(function, types)

TypeError: concatenate() got an unexpected keyword argument 'dtype'
```

**Comment by ConorMacBride** [comment] 2023-02-04 11:03
Which version of sunpy and astropy do you have installed? Our tests are passing with numpy 1.24.1 https://github.com/sunpy/sunpy/actions/runs/4079779931/jobs/7031513158#step:9:74

**Comment by exitflynn** [comment] 2023-02-04 11:08
i wonder what caused this, i installed the latest versions of all dependencies in a clean venv and tried to replicate this but couldn't
```
>>> import numpy
>>> numpy.__version__
'1.24.1'
>>> import sunpy.map
>>>
```
maybe the issue is caused by an old astropy version? (highly unlikely though) :thinking:

**Comment by Jett-Code** [comment] 2023-02-04 19:20
I've tested it and according to the conclusion if you have not installed matplotlib then this error occurs, to make it run do this
`pip install matplotlib` and then run the following command, there will be no errors after that.

**Comment by exitflynn** [comment] 2023-02-05 07:57
@Jett-Code i could be wrong but i think that you could be talking about the ModuleNotFound error that occurs on `import sunpy.map`'ing after doing a fresh `pip install sunpy`. The error here is tracing back quite a bit going by the error log.

**Comment by STBadman** [comment] 2023-02-06 22:00
I also found `sunpy` was no longer importing successfully after updating `numpy`, and the fix was updating _both_ `sunpy` and `astropy`. 

The following setup was working previously 

`astropy==5.1`
`numpy==1.21.5`
`sunpy==4.1.0`

I then updated numpy to `1.24.2` and got a similar error stack to @AlexPietrow when doing just `import sunpy.coordinates` 

Then updating

`sunpy==4.1.2`
`astropy==5.2.1` 

everything is working again.

**Comment by dstansby** [comment] 2023-02-07 13:23
I think this is a duplicate of https://github.com/astropy/astropy/issues/14210, so updating your astropy version should fix it. Thanks for the clear report!

**Closed by dstansby** 2023-02-07 13:23 UTC
Labels: Question

**Comment by AlexPietrow** [comment] 2023-02-08 08:09
Updating astropy was indeed the solution, thank you all!
