### ISSUE TITLE
Fido download of EIS data stops at 80% resulting in corrupt files

### ISSUE THREAD

**Issue by Laubeee** [sunpy/sunpy#5012] opened 2021-02-18 10:58 UTC
### Description
Fido download of Hinode EIS data stops at 80% resulting in corrupt files.

### Expected vs Actual behavior
1. Files should be downloaded fully, not just 80%
2. If somehow that is not possible, an actual error should be raised instead of just continuing as if everything succeeded

### Steps to Reproduce
```python
from sunpy.net import Fido, attrs
res = Fido.search(attrs.Instrument('EIS'), attrs.Time("2015-07-18T11:59:46.670", "2015-07-18T15:50:41.659"))
downloaded_files = Fido.fetch(res, path="eis_obs")  # download is corrupt..
```

### System Details
- SunPy Version: 2.0.5 / 2.0.7
- Astropy Version: 4.0 / 4.2
- Python Version: 3.7.2
- OS information: win10

**Comment by nabobalis** [comment] 2021-02-18 11:19
Can you tell me what version of parfive you have installed?

**Comment by Laubeee** [comment] 2021-02-18 11:38
> Can you tell me what version of parfive you have installed?

1.2.0

> The partial files look like this on disk:
> 
> ```
> <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
> <html><head>
> <title>403 Forbidden</title>
> </head><body>
> <h1>Forbidden</h1>
> <p>You don't have permission to access /data/hinode/eis/level0/2015/07/18/eis_l0_20150718_114126.fits.gz
> on this server.</p>
> </body></html>
> ^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
> ```

Indeed! I didn't check tbh I just thought they were only partially downloaded.

**Comment by Cadair** [comment] 2021-02-18 14:04
This looks like a VSO issue if it's serving files with incorrect content.

**Comment by dstansby** [comment] 2021-02-18 14:58
I came across this the other week too, thanks for reporting and thanks @nabobalis for taking a closer look!

**Comment by nabobalis** [comment] 2021-02-18 15:04
I want to get the URLS out of fido and see if I can download it through my browser ok.

**Comment by Cadair** [comment] 2021-02-18 15:37
I have brought this up with the VSO team, am pretty sure it's a server side issue.

**Comment by ejm4567** [comment] 2021-02-18 16:18
The mount containing the Hinode data is up and responding. I was able to download that 11:41 7/18/15 EIS tarball using both the VSO web client and IDL/SSW.  The download did fail for that particular file using my SunPy test script. Other EIS file are downloaded by my SunPy script.

Interestingly, that particular file was a lot slower downloading via IDL/SSW than others:

`5 : https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_114126.fits.gz
% SOCK_GET_MAIN: 42947405 bytes of eis_l0_20150718_114126.fits.gz copied in 200.79 seconds.`

vs,

`9 : https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_054203.fits.gz
% SOCK_GET_MAIN: 1670876 bytes of eis_l0_20150718_054203.fits.gz copied in 8.49 seconds.`

Not sure if the problem is in Fido, parfive, or elsewhere in SunPy.  It does seem to be SunPy-specific.

**Comment by Cadair** [comment] 2021-02-18 16:25
Why would the sunpy download code cause that file to have that content though? I could understand maybe parfive timing out on that file (there are timeouts but I would expect errors if they were hit), but we can't be pulling the content from anywhere else other than what the VSO sends us?

**Comment by Cadair** [comment] 2021-02-18 16:29
The download URLs as returned by VSOClient:
```
<getdataitem>
            <dataitem>
              <provider>SDAC_EIS</provider>
              <fileiditem>
                <fileid>eis/level0/2015/07/18/eis_l0_20150718_114126.fits.gz</fileid>
              </fileiditem>
              <url>https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_114126.fits.gz</url>
            </dataitem>
            <dataitem>
              <fileiditem>
                <fileid>eis/level0/2015/07/18/eis_l0_20150718_131926.fits.gz</fileid>
              </fileiditem>
              <url>https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_131926.fits.gz</url>
              <provider>SDAC_EIS</provider>
            </dataitem>
          </getdataitem>
          ```

**Comment by Cadair** [comment] 2021-02-18 16:30
cracking open one of them in my terminal seems to work, so I assume it's some header we are sending when we try and download the file that's causing the issue.

**Comment by Cadair** [comment] 2021-02-18 17:10
The issue appears to be that parfive will attempt to download the file in chunks to speed up the transfer, if the response from the server on the GET request includes the `Accept-Ranges: bytes` header (which in this case it does). However, if we then request segments of the file with the `Range: ` header present the content becomes corrupted.

I will shortly open a PR to parfive with the branch I used to debug this as I added some env vars and logging, however, this is an issue with the behaviour of the VSO server.

**Comment by dstansby** [comment] 2021-03-17 21:15
Is there a workaround for this? I'm finding exactly the same issue trying to download WISPR data.

**Comment by Cadair** [comment] 2021-03-19 16:43
Specify your own parfive downloader instance with `max_splits=0`.

**Comment by dstansby** [comment] 2021-04-20 17:34
Can we set max_splits=0 within sunpy by default? Just came across this again for GONG synoptic maps, and it's a really annoying bug (I had to manually delete the half-downloaded file, work out how to create my own `Downloader()`, and then run my code again)

**Comment by dstansby** [comment] 2021-04-20 18:49
Apologies for the false alarm, I appear to be able to download GONG files fine, and I think the one that partially downloaded was a transient network issue. The code I was using was:

```python
from sunpy.net import Fido
from sunpy.net import attrs as a

t = a.Time('2020-05-28', '2020-05-29')
res = Fido.search(t & a.Instrument('GONG'))
files = Fido.fetch(res[0, 0])
```

**Comment by Cadair** [comment] 2021-04-20 19:05
It might be a good idea to disable splits for providers in the VSO client for everything but whitelisted providers. But this will take some work and it would just be a work around.

**Comment by ejm4567** [comment] 2021-04-26 17:04
I've removed the mod_security Rule #958291 that was causing the initial error in downloading EIS data. Turns out only EIS and MEES data (that I know of) are .gzipped at SDAC.

With Rule #958291 removed, one can see the Range request being processed, here for a MEES file:

`
63.225.X.Y - - [23/Apr/2021:13:24:24 -0400] "GET /data/mees/MCCD/Level_0.5/200702/MCIS_20070205_171714.scan.fits.gz HTTP/1.1" 206 4

63.225.X.Y - - [23/Apr/2021:13:24:22 -0400] "GET /data/mees/MCCD/Level_0.5/200702/MCIS_20070205_171714.scan.fits.gz HTTP/1.1" 206 33855579

63.225.X.Y - - [23/Apr/2021:13:24:22 -0400] "GET /data/mees/MCCD/Level_0.5/200702/MCIS_20070205_171714.scan.fits.gz HTTP/1.1" 206 33855579

63.225.X.Y - - [23/Apr/2021:13:24:22 -0400] "GET /data/mees/MCCD/Level_0.5/200702/MCIS_20070205_171714.scan.fits.gz HTTP/1.1" 206 33855579

63.225.X.Y - - [23/Apr/2021:13:24:22 -0400] "GET /data/mees/MCCD/Level_0.5/200702/MCIS_20070205_171714.scan.fits.gz HTTP/1.1" 206 33855579

63.225.X.Y - - [23/Apr/2021:13:24:22 -0400] "GET /data/mees/MCCD/Level_0.5/200702/MCIS_20070205_171714.scan.fits.gz HTTP/1.1" 206 33855579`

63.225.X.Y - - [23/Apr/2021:13:44:55 -0400] "GET /data/mees/MCCD/Level_0.5/200702/MCIS_20070205_193304.scan.fits.gz HTTP/1.1" 200 178429659
`

Yet the files that are downloaded, while complete, for EIS and MEES are _not_ decompressionable:
`vi eis_l0_20150718_001226_fits.gz

"eis_l0_20150718_001226_fits.gz" [noeol] 104435L, 43329622C
Error detected while processing function gzip#read:
line   44:
Error: Could not read uncompressed file
Press ENTER or type command to continue

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /data/hinode/eis/level0/2015/07/18/eis_l0_20150718_001226.fits.gz
on this server.</p>
</body></html>`

In the case of EIS, the file has a 403 still in it, causing the file to not be read by gunzip, hence the error seen. I have of course checked file permissions, and they are correct. I've also adjusted the Apache config to have

`AddEncoding x-compress .Z
  AddEncoding x-gzip .gz .tgz`

so that Parfive should indeed receive a correct .gz file from the Range request. I've also tested the transfer of the same data files for EIS and MEES via the VSO web client, and indeed get the full expected file which _can_ be decompressed and is readable.

It looks like the final problem might be on the Python side of the request.

Turns out there are at least two outstanding bugs known in aiohttp about chunked transfers:

[​https://github.com/aio-libs/aiohttp/issues/4435](url)

[​https://github.com/aio-libs/aiohttp/issues/4462](url)

which seems due to a design of aiohttp itself if I read the documentation correctly:

> chunked (int) – Enable chunked transfer encoding. It is up to the developer to decide how to chunk data streams. If chunking is enabled, aiohttp encodes the provided chunks in the “Transfer-encoding: chunked” format. If chunked is set, then the Transfer-encoding and content-length headers are disallowed. None by default (optional).

[https://docs.aiohttp.org/en/stable/client_reference.html](url)

One possible solution is to overload the Parfive method _get_http to use requests instead of aiohttp for the case of Range requests of small numbers of individual .gz files. For the case of "staged" tarball requests of data from SDAC, more coding in Parfive will most likely be needed, but I'm not sure that type of request is done very often. 

Range requests from SunPy 2.1 for uncompressed data such as EUNIS or WISPR do indeed work:

`63.225.X.Y - - [23/Apr/2021:12:23:59 -0400] "GET /data/psp/wispr/L1/20190410/psp_L1_wispr_20190410T021829_V1_1221.fits HTTP/1.1" 206 3150145

63.225.X.Y - - [23/Apr/2021:12:23:59 -0400] "GET /data/psp/wispr/L1/20190410/psp_L1_wispr_20190410T021829_V1_1221.fits HTTP/1.1" 206 3150145

63.225.X.Y - - [23/Apr/2021:12:23:59 -0400] "GET /data/psp/wispr/L1/20190410/psp_L1_wispr_20190410T021829_V1_1221.fits HTTP/1.1" 206 3150145

63.225.X.Y - - [23/Apr/2021:12:23:59 -0400] "GET /data/psp/wispr/L1/20190410/psp_L1_wispr_20190410T021829_V1_1221.fits HTTP/1.1" 200 15750720`

**Comment by Cadair** [comment] 2021-06-23 10:33
hey @ejm4567 I *finally* came back to look at this. I have to disagree with your assessment, I do not think this is an aiohttp bug.

My opinion can be (hopefully) backed up with the following shell one liner:


```
$ http -v https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_131926.fits.gz 'Range: bytes=0-8589481'

GET /data/hinode/eis/level0/2015/07/18/eis_l0_20150718_131926.fits.gz HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: sdac.virtualsolar.org
Range: bytes=0-8589481
User-Agent: HTTPie/2.4.0



HTTP/1.1 403 Forbidden
Connection: close
Content-Length: 266
Content-Type: text/html; charset=iso-8859-1
Date: Wed, 23 Jun 2021 10:01:56 GMT
Server: Apache
Strict-Transport-Security: max-age=31536000; includeSubDomains

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /data/hinode/eis/level0/2015/07/18/eis_l0_20150718_131926.fits.gz
on this server.</p>
</body></html>
```

This shows a few things, that I think disproves your theory. One, the response headers have neither `Content-Encoding` or `Transfer-Encoding` headers, which I would *hope* makes the two aiohttp bugs you linked to not applicable. (aiohttp could be looking at `Content-Type` but it really shouldn't be).

The other more conclusive thing is that I can recreate this bug with nothing but a simple [`http`](https://httpie.io/) call, just by setting the `Range` header to request the first chunk of the file.


This actually get's weirder if you then study the further requests for subsequent chunks. As you can see in the example above the first chunk is actually coming back with a `Content-Type: text/html; charset=iso-8859-1` header in it (which makes sense, it's an error page), but then if you are to request the next chunk:

```
$ http -v https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_131926.fits.gz 'Range: bytes=8589481-17178962'

GET /data/hinode/eis/level0/2015/07/18/eis_l0_20150718_131926.fits.gz HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: sdac.virtualsolar.org
Range: bytes=8589481-17178962
User-Agent: HTTPie/2.4.0



HTTP/1.1 206 Partial Content
Accept-Ranges: bytes
Connection: close
Content-Length: 8589482
Content-Range: bytes 8589481-17178962/29463576
Content-Type: application/x-gzip
Date: Wed, 23 Jun 2021 10:10:40 GMT
ETag: "1c19418-51bcbff4b76c0"
Last-Modified: Sun, 26 Jul 2015 19:10:59 GMT
Server: Apache
Strict-Transport-Security: max-age=31536000; includeSubDomains

+-----------------------------------------+
| NOTE: binary data not shown in terminal |
+-----------------------------------------+
```


The request completes, returns a content type of `Content-Type: application/x-gzip` (which is what I would expect) and returns binary data. From a quick comparison of the data that is returned by this second request against the file downloaded without using ranges, **this second response is actually a real chunk of the gzip file**. So it's only the a request with `Range = 0-` in it which is failing with a 403.

For comparison between what parfive is doing and what my http requests above are, here is the complete output from parfive's logging with extra logging added to show the response headers:

<details>

```
parfive - DEBUG - Configured parfive to run with debug logging...
parfive - DEBUG - GET request made to https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_131926.fits.gz with headers=<CIMultiDictProxy('Host': 'sdac.virtualsolar.org', 'User-Agent': 'sunpy/3.1.dev102+gdea962788 parfive/1.2.1.dev9+gad816aa.d20210623 aiohttp/3.7.3 python/3.9.5', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate')>
parfive - DEBUG - Response received from https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_131926.fits.gz with headers=<CIMultiDictProxy('Date': 'Wed, 23 Jun 2021 10:29:03 GMT', 'Server': 'Apache', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Last-Modified': 'Sun, 26 Jul 2015 19:10:59 GMT', 'Etag': '"1c19418-51bcbff4b76c0"', 'Accept-Ranges': 'bytes', 'Content-Length': '29463576', 'Connection': 'close', 'Content-Type': 'application/x-gzip')>
parfive - DEBUG - GET request made to https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_114126.fits.gz with headers=<CIMultiDictProxy('Host': 'sdac.virtualsolar.org', 'User-Agent': 'sunpy/3.1.dev102+gdea962788 parfive/1.2.1.dev9+gad816aa.d20210623 aiohttp/3.7.3 python/3.9.5', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate')>
parfive - DEBUG - Response received from https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_114126.fits.gz with headers=<CIMultiDictProxy('Date': 'Wed, 23 Jun 2021 10:29:03 GMT', 'Server': 'Apache', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Last-Modified': 'Sun, 26 Jul 2015 19:10:59 GMT', 'Etag': '"28f534d-51bcbff4b76c0"', 'Accept-Ranges': 'bytes', 'Content-Length': '42947405', 'Connection': 'close', 'Content-Type': 'application/x-gzip')>
parfive - DEBUG - GET request made to https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_131926.fits.gz with headers=<CIMultiDictProxy('Host': 'sdac.virtualsolar.org', 'User-Agent': 'sunpy/3.1.dev102+gdea962788 parfive/1.2.1.dev9+gad816aa.d20210623 aiohttp/3.7.3 python/3.9.5', 'Range': 'bytes=17678145-23570860', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate')>
parfive - DEBUG - Response received from https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_131926.fits.gz with headers=<CIMultiDictProxy('Date': 'Wed, 23 Jun 2021 10:29:03 GMT', 'Server': 'Apache', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Last-Modified': 'Sun, 26 Jul 2015 19:10:59 GMT', 'Etag': '"1c19418-51bcbff4b76c0"', 'Accept-Ranges': 'bytes', 'Content-Length': '5892716', 'Content-Range': 'bytes 17678145-23570860/29463576', 'Connection': 'close', 'Content-Type': 'application/x-gzip')>
parfive - DEBUG - GET request made to https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_131926.fits.gz with headers=<CIMultiDictProxy('Host': 'sdac.virtualsolar.org', 'User-Agent': 'sunpy/3.1.dev102+gdea962788 parfive/1.2.1.dev9+gad816aa.d20210623 aiohttp/3.7.3 python/3.9.5', 'Range': 'bytes=29463575-', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate')>
parfive - DEBUG - Response received from https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_131926.fits.gz with headers=<CIMultiDictProxy('Date': 'Wed, 23 Jun 2021 10:29:03 GMT', 'Server': 'Apache', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Last-Modified': 'Sun, 26 Jul 2015 19:10:59 GMT', 'Etag': '"1c19418-51bcbff4b76c0"', 'Accept-Ranges': 'bytes', 'Content-Length': '1', 'Content-Range': 'bytes 29463575-29463575/29463576', 'Connection': 'close', 'Content-Type': 'application/x-gzip')>
parfive - DEBUG - GET request made to https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_114126.fits.gz with headers=<CIMultiDictProxy('Host': 'sdac.virtualsolar.org', 'User-Agent': 'sunpy/3.1.dev102+gdea962788 parfive/1.2.1.dev9+gad816aa.d20210623 aiohttp/3.7.3 python/3.9.5', 'Range': 'bytes=17178962-25768443', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate')>
parfive - DEBUG - Response received from https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_114126.fits.gz with headers=<CIMultiDictProxy('Date': 'Wed, 23 Jun 2021 10:29:03 GMT', 'Server': 'Apache', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Last-Modified': 'Sun, 26 Jul 2015 19:10:59 GMT', 'Etag': '"28f534d-51bcbff4b76c0"', 'Accept-Ranges': 'bytes', 'Content-Length': '8589482', 'Content-Range': 'bytes 17178962-25768443/42947405', 'Connection': 'close', 'Content-Type': 'application/x-gzip')>
parfive - DEBUG - GET request made to https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_131926.fits.gz with headers=<CIMultiDictProxy('Host': 'sdac.virtualsolar.org', 'User-Agent': 'sunpy/3.1.dev102+gdea962788 parfive/1.2.1.dev9+gad816aa.d20210623 aiohttp/3.7.3 python/3.9.5', 'Range': 'bytes=0-5892715', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate')>
parfive - DEBUG - Response received from https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_131926.fits.gz with headers=<CIMultiDictProxy('Date': 'Wed, 23 Jun 2021 10:29:03 GMT', 'Server': 'Apache', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Content-Length': '266', 'Connection': 'close', 'Content-Type': 'text/html; charset=iso-8859-1')>
parfive - DEBUG - GET request made to https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_131926.fits.gz with headers=<CIMultiDictProxy('Host': 'sdac.virtualsolar.org', 'User-Agent': 'sunpy/3.1.dev102+gdea962788 parfive/1.2.1.dev9+gad816aa.d20210623 aiohttp/3.7.3 python/3.9.5', 'Range': 'bytes=11785430-17678145', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate')>
parfive - DEBUG - Response received from https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_131926.fits.gz with headers=<CIMultiDictProxy('Date': 'Wed, 23 Jun 2021 10:29:03 GMT', 'Server': 'Apache', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Last-Modified': 'Sun, 26 Jul 2015 19:10:59 GMT', 'Etag': '"1c19418-51bcbff4b76c0"', 'Accept-Ranges': 'bytes', 'Content-Length': '5892716', 'Content-Range': 'bytes 11785430-17678145/29463576', 'Connection': 'close', 'Content-Type': 'application/x-gzip')>
parfive - DEBUG - GET request made to https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_131926.fits.gz with headers=<CIMultiDictProxy('Host': 'sdac.virtualsolar.org', 'User-Agent': 'sunpy/3.1.dev102+gdea962788 parfive/1.2.1.dev9+gad816aa.d20210623 aiohttp/3.7.3 python/3.9.5', 'Range': 'bytes=5892715-11785430', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate')>
parfive - DEBUG - Response received from https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_131926.fits.gz with headers=<CIMultiDictProxy('Date': 'Wed, 23 Jun 2021 10:29:03 GMT', 'Server': 'Apache', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Last-Modified': 'Sun, 26 Jul 2015 19:10:59 GMT', 'Etag': '"1c19418-51bcbff4b76c0"', 'Accept-Ranges': 'bytes', 'Content-Length': '5892716', 'Content-Range': 'bytes 5892715-11785430/29463576', 'Connection': 'close', 'Content-Type': 'application/x-gzip')>
parfive - DEBUG - GET request made to https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_114126.fits.gz with headers=<CIMultiDictProxy('Host': 'sdac.virtualsolar.org', 'User-Agent': 'sunpy/3.1.dev102+gdea962788 parfive/1.2.1.dev9+gad816aa.d20210623 aiohttp/3.7.3 python/3.9.5', 'Range': 'bytes=25768443-34357924', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate')>
parfive - DEBUG - Response received from https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_114126.fits.gz with headers=<CIMultiDictProxy('Date': 'Wed, 23 Jun 2021 10:29:03 GMT', 'Server': 'Apache', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Last-Modified': 'Sun, 26 Jul 2015 19:10:59 GMT', 'Etag': '"28f534d-51bcbff4b76c0"', 'Accept-Ranges': 'bytes', 'Content-Length': '8589482', 'Content-Range': 'bytes 25768443-34357924/42947405', 'Connection': 'close', 'Content-Type': 'application/x-gzip')>
parfive - DEBUG - GET request made to https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_131926.fits.gz with headers=<CIMultiDictProxy('Host': 'sdac.virtualsolar.org', 'User-Agent': 'sunpy/3.1.dev102+gdea962788 parfive/1.2.1.dev9+gad816aa.d20210623 aiohttp/3.7.3 python/3.9.5', 'Range': 'bytes=23570860-29463575', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate')>
parfive - DEBUG - Response received from https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_131926.fits.gz with headers=<CIMultiDictProxy('Date': 'Wed, 23 Jun 2021 10:29:03 GMT', 'Server': 'Apache', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Last-Modified': 'Sun, 26 Jul 2015 19:10:59 GMT', 'Etag': '"1c19418-51bcbff4b76c0"', 'Accept-Ranges': 'bytes', 'Content-Length': '5892716', 'Content-Range': 'bytes 23570860-29463575/29463576', 'Connection': 'close', 'Content-Type': 'application/x-gzip')>
parfive - DEBUG - GET request made to https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_114126.fits.gz with headers=<CIMultiDictProxy('Host': 'sdac.virtualsolar.org', 'User-Agent': 'sunpy/3.1.dev102+gdea962788 parfive/1.2.1.dev9+gad816aa.d20210623 aiohttp/3.7.3 python/3.9.5', 'Range': 'bytes=0-8589481', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate')>
parfive - DEBUG - Response received from https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_114126.fits.gz with headers=<CIMultiDictProxy('Date': 'Wed, 23 Jun 2021 10:29:04 GMT', 'Server': 'Apache', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Content-Length': '266', 'Connection': 'close', 'Content-Type': 'text/html; charset=iso-8859-1')>
parfive - DEBUG - GET request made to https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_114126.fits.gz with headers=<CIMultiDictProxy('Host': 'sdac.virtualsolar.org', 'User-Agent': 'sunpy/3.1.dev102+gdea962788 parfive/1.2.1.dev9+gad816aa.d20210623 aiohttp/3.7.3 python/3.9.5', 'Range': 'bytes=34357924-', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate')>
parfive - DEBUG - Response received from https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_114126.fits.gz with headers=<CIMultiDictProxy('Date': 'Wed, 23 Jun 2021 10:29:04 GMT', 'Server': 'Apache', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Last-Modified': 'Sun, 26 Jul 2015 19:10:59 GMT', 'Etag': '"28f534d-51bcbff4b76c0"', 'Accept-Ranges': 'bytes', 'Content-Length': '8589481', 'Content-Range': 'bytes 34357924-42947404/42947405', 'Connection': 'close', 'Content-Type': 'application/x-gzip')>
parfive - DEBUG - GET request made to https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_114126.fits.gz with headers=<CIMultiDictProxy('Host': 'sdac.virtualsolar.org', 'User-Agent': 'sunpy/3.1.dev102+gdea962788 parfive/1.2.1.dev9+gad816aa.d20210623 aiohttp/3.7.3 python/3.9.5', 'Range': 'bytes=8589481-17178962', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate')>
parfive - DEBUG - Response received from https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_114126.fits.gz with headers=<CIMultiDictProxy('Date': 'Wed, 23 Jun 2021 10:29:04 GMT', 'Server': 'Apache', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Last-Modified': 'Sun, 26 Jul 2015 19:10:59 GMT', 'Etag': '"28f534d-51bcbff4b76c0"', 'Accept-Ranges': 'bytes', 'Content-Length': '8589482', 'Content-Range': 'bytes 8589481-17178962/42947405', 'Connection': 'close', 'Content-Type': 'application/x-gzip')>
```

</details>

and here is the relevant parts:

```
parfive - DEBUG - GET request made to https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_131926.fits.gz with headers=<CIMultiDictProxy('Host': 'sdac.virtualsolar.org', 'User-Agent': 'sunpy/3.1.dev102+gdea962788 parfive/1.2.1.dev9+gad816aa.d20210623 aiohttp/3.7.3 python/3.9.5', 'Range': 'bytes=0-5892715', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate')>
parfive - DEBUG - Response received from https://sdac.virtualsolar.org/data/hinode/eis/level0/2015/07/18/eis_l0_20150718_131926.fits.gz with headers=<CIMultiDictProxy('Date': 'Wed, 23 Jun 2021 10:29:03 GMT', 'Server': 'Apache', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Content-Length': '266', 'Connection': 'close', 'Content-Type': 'text/html; charset=iso-8859-1')>
```

You can see the request headers are the same with the exception of the `User-Agent` and the presence of a `Connection` header (and in this case the size of the range apparently).


Sorry to throw this back at you, but given I can reproduce this bug without even using aiohttp, I have to assume it's still on the VSO side.

**Comment by ejm4567** [comment] 2021-06-25 14:11
You are correct Stuart. The 403 is coming from mod_security on the gateway machine:

`ModSecurity: Access denied with code 403 (phase 2). String match "bytes=0-"`

I've removed the rule from the gateway machine and now get a full, compressed EIS file that can be de-compressed.

Please test again and let me know if you still see issues.

**Comment by Cadair** [comment] 2021-06-25 14:51
This now appears to work on my machine, so I am going to close this. If anyone runs into something similar in the future or can't make this example work please comment.

Thanks so much for all your work on this @ejm4567 it's great working with the VSO

**Closed** 2021-06-25 14:51 UTC
Labels: Affects Dev, Affects Release, Bug(?), Remote Server Issue / VSO, Upstream Fix Required, net
