### ISSUE TITLE
Add ability to download files from AIA cutout service

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#1469] opened 2015-06-23 13:55 UTC
Here is the equivalent IDL code 

http://darts.isas.jaxa.jp/pub/ssw/vobs/ontology/idl/ssw_service_get_data.pro

and here is a page with actual data and the code used to download the data.

http://www.lmsal.com/solarsoft/ssw_service/queue/finished/ssw_service_150623_062824_33488.html

**Comment by Cadair** [comment] 2015-06-23 13:57
you can do this through JSOC right? Also is there not already an issue for this?

**Comment by Cadair** [comment] 2015-06-23 13:57
duplicate of #1259

**Closed by Cadair** 2015-06-23 13:57 UTC
Labels: Feature Request

**Comment by ehsteve** [comment] 2015-06-23 14:01
No, this is not related to JSOC. Thanks for noticing the duplicate.

**Comment by Cadair** [comment] 2015-06-23 14:02
@ehsteve I know there is a separate service, but JSOC can also do AIA & HMI cutouts.

**Comment by Cadair** [comment] 2015-06-23 14:02
see #1259 for a similar discussion with @wafels
