### ISSUE TITLE
Inconsistent norm init behavior of MDIMap and HMIMap

### ISSUE THREAD

**Issue by ZeyuSun** [sunpy/sunpy#5637] opened 2021-10-26 18:54 UTC
### Description
[HMIMap](https://github.com/sunpy/sunpy/blob/6e4c8486c39310871a93e8c7c5f5d0d46206ce5e/sunpy/map/sources/sdo.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L109-L111) does not enforce `vmin` and `vmax` but [MDIMap](https://github.com/sunpy/sunpy/blob/6e4c8486c39310871a93e8c7c5f5d0d46206ce5e/sunpy/map/sources/soho.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L183-L189) does. Is there any reason for this different behavior?

Digging into the history, it seems this commit 55610e9cad745033a19b41c1ecf26e472df9da3b added vmin/vmax for soho.py but not for sdo.py.

### Expected vs Actual behavior

I think it makes sense to not set `vmin` and `vmax` in the constructor. Otherwise the following code gives an error for MDIMap but not for HMIMap:
```python
hmi_map.plot(cmap='hmimag', vmin=-1500, vmax=1500)  # No error
mdi_map.plot(cmap='hmimag', vmin=-1500, vmax=1500)  # ValueError: Cannot manually specify vmin, as the norm already has vmin set
```
This is because we [check if norm has been set during plotting](https://github.com/sunpy/sunpy/blob/82a7a2574b09736285427af54be82887a80f93af/sunpy/map/mapbase.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L2489-L2500).

### System Details

- SunPy Version: v3.0.2
- Astropy Version:
- Python Version:
- OS information:

**Comment by dstansby** [comment] 2022-01-19 15:36
I think this is expected behaviour where we are erroring instead of trying to choose between two {vmin, vmax} values (one set on the norm, and one passed to `plot`). I have improved the error message here: https://github.com/sunpy/sunpy/pull/5824 - any feedback welcome!

This is inconsistent because we explicitly set a symmetric vmin/vmax about zero on MDIMap, but not on HMIMap. We probably should set this on HMIMap too so zero is at the center of the colorbar.

**Comment by dstansby** [comment] 2022-05-31 08:54
I think this is fixed by the above PRs

**Closed as completed** 2022-05-31 14:52 UTC
Labels: map, Discussion
