### ISSUE TITLE
Axis label missing on two figure tests

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#2654] opened 2018-06-14 13:44 UTC
Running the figure tests and checking at least the output from my fork and the same on master.

The axis labels for the figure tests `test_heliographic_peek` and **`test_heliographic_rectangle` are missing.

I get two differences between:

Old
![sunpy map tests test_plotting test_heliographic_peek](https://user-images.githubusercontent.com/1392107/41415697-12045f36-6fe1-11e8-9d9a-11e1421a09ff.png)
![sunpy map tests test_plotting test_heliographic_rectangle](https://user-images.githubusercontent.com/1392107/41415698-122798f2-6fe1-11e8-8206-ffa1a994aa06.png)

Current:
![sunpy map tests test_plotting test_heliographic_peek](https://user-images.githubusercontent.com/1392107/41415703-150d3194-6fe1-11e8-9ad9-e3b3d41505fb.png)
![sunpy map tests test_plotting test_heliographic_rectangle](https://user-images.githubusercontent.com/1392107/41415705-1529c502-6fe1-11e8-9fc4-3e0d5ce68903.png)

Update: The axis labels come back if I use an older env which we will soon be using again for the figure tests. I would assume the largest difference is that the older env is Astropy 2 while we will want to be using Astropy 3.

**Comment by dstansby** [comment] 2018-06-14 13:58
When you say "your fork", what do you mean? I've just regenerated the figures from the master branch and they seem fine (w/ axis labels) to me.

**Comment by nabobalis** [comment] 2018-06-14 14:05
Sorry, I was on my own fork off master. But I just checked master and it seems to missing there.

**Comment by Cadair** [comment] 2018-10-11 18:44
This is actually a bug in wcsaxes where the ticks and the axes labels are not show if the edge of the wcs doesn't make it to the frame. The issue is in this case it should behave like it does as you are bounding the plot and the wcs at the same place.

**Comment by dstansby** [comment] 2020-08-18 17:44
Still looks like an issue, I think the problem is what limits are being set on the plots internally by sunpy.

**Comment by dstansby** [comment] 2020-08-23 18:18
If anyone wants to reproduce locally,

```python
import sunpy.map
import sunpy.data.test
import os

testpath = sunpy.data.test.rootdir
m = sunpy.map.Map(os.path.join(testpath, 'heliographic_phase_map.fits.gz'))
m.peek()
```

**Comment by dstansby** [comment] 2020-10-17 16:58
This is because the WCS information is wrong in these files, such that the bottom left of the bottom left pixel does not have a valid transformation to world coordiantes, so as expected the coordinate axes do not draw with the default lims. I've checked that the limit setting etc. is working fine, so I'm going to close this.

**Closed by dstansby** 2020-10-17 16:58 UTC
Labels: Bug(?), Effort Low, Package Intermediate, Priority Low, Tests, Upstream Fix Required
