### ISSUE TITLE
Not reading correct time for all SOHO data for Level 0 data

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#3070] opened 2019-04-25 13:51 UTC
### Description

The SOHO clock drifts over time and that drift is not accounted for in the standard `DATE-OBS` fits header. The correct time is available in the FITS header under a `COMMENT` field.

**Comment by Cadair** [comment] 2019-04-26 09:22
(ﾉ≧∇≦)ﾉ ﾐ ┸━┸

**Comment by dpshelio** [comment] 2019-05-12 21:07
Does this apply to every instrument? Do all level-0 files have such comment? Do they follow the same date format? So many questions... (including, do I need to re-analyse the data from my Phd?)

**Comment by ehsteve** [comment] 2019-05-13 17:28
FYI, I anecdotally heard that this may not be a problem anymore. We really need someone that is very familiar with SOHO data to chime in here.

**Comment by sudozer** [comment] 2019-05-13 18:16
Let me touch base with some of our ESA people and see if we can at least get a better understanding of what the situation here is.  Stay tuned.

**Comment by jhourcle** [comment] 2019-05-13 19:09
the VSO is using the times from ESA's 'SOHOCAT' data catalog ... and I have confirmed that the EIT L0 data in there is *uncorrected*.  I suspect that it would be true for all SOHO L0 data, as I believe the correction was considered to be 'calibration' so not fixed 'til L1.

**Comment by nabobalis** [comment] 2019-05-22 15:04
Did #3067 help this problem?

**Comment by ayshih** [comment] 2019-05-22 15:28
I don't think #3067 is relevant.

Our sample EIT file has the corrected `DATE-OBS`, but our test EIT files do not.  Presumably the test EIT files are Level-0 data?  As long as all Level-1 files have the corrected `DATE-OBS`, does SunPy need to worry about this issue?

**Comment by ehsteve** [comment] 2019-06-19 16:43
The fix for this should be to issue a warning if reading anything below Level 1 data where this issue not fixed.

**Comment by dstansby** [comment] 2020-04-02 11:40
Do you know how we tell if the issue is or isn't fixed in a <L1 data file?

**Comment by dstansby** [comment] 2020-08-23 18:27
Can someone provide a sample L0 data file that has this issue?

**Comment by dstansby** [comment] 2020-11-24 20:39
Since there's been no response, I'm going to close this as "can't fix". If someone can link to a file that has this issue feel free to comment below and/or re-open

**Closed by dstansby** 2020-11-24 20:39 UTC
Labels: Affects Dev, Affects Release, Bug(?), Effort Medium, Package Novice, Priority Medium, Solar Physics Knowledge, map
