### ISSUE TITLE
We aren't sending Detector attr to VSO (Fido downloads the wrong LASCO data)

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#4533] opened 2020-10-01 14:18 UTC
### Description

LASCO C3 data is downloaded instead of the requested LASCO C2 data (as pointed out by issue #4519, the example claims to download and display LASCO C3 data, but this is not the case).

### Expected vs Actual behavior

I expected that LASCO C3 data would be downloaded and displayed.

### Steps to Reproduce

```python
from sunpy.net import Fido, attrs as a
from sunpy.io.file_tools import read_file

timerange = a.Time('2002/05/24 11:06', '2002/05/24 11:07') 
instrument = a.Instrument.lasco 
detector = a.Detector.c3 
result = Fido.search(timerange, instrument) 
downloaded_files = Fido.fetch(result)
data, header = read_file(downloaded_files[0])[0]

header                                                                                                                          
Out[7]: 
FileHeader([('SIMPLE', True),
            ('BITPIX', -32),
            ('NAXIS', 2),
            ('NAXIS1', 1024),
            ('NAXIS2', 1024),
            ('DATE', '2012-12-01T06:16:06.671'),
            ('FILENAME', '25119649.fts'),
            ('FILEORIG', '020524_110812.img'),
            ('DATE-OBS', '2002-05-24T11:05:48.893'),
            ('TIME-OBS', ''),
            ('EXPTIME', 26.0934819641),
            ('TELESCOP', 'SOHO'),
            ('INSTRUME', 'LASCO'),
            ('DETECTOR', 'C2'),
            ('READPORT', 'C'),
            ('SUMROW', 0),
            ('SUMCOL', 0),
            ('LEBXSUM', 1),
            ('LEBYSUM', 1),
            ('FILTER', 'Orange'),
            ('POLAR', 'Clear'),
            ('COMPRSSN', 'X%'),
            ('MID_DATE', 52418),
            ('MID_TIME', 39978.8),
            ('R1COL', 20),
            ('R1ROW', 1),
            ('R2COL', 1043),
            ('R2ROW', 1024),
            ('LEVEL', '1.0'),
            ('RECTIFY', 0.0),
            ('CRPIX1', 510.79),
            ('CRPIX2', 506.83),
            ('CROTA', 0.489091),
            ('CROTA1', 0.489091),
            ('CROTA2', 0.489091),
            ('CRVAL1', 0),
            ('CRVAL2', 0),
            ('CTYPE1', 'HPLN-TAN'),
            ('CTYPE2', 'HPLT-TAN'),
            ('CUNIT1', 'arcsec'),
            ('CUNIT2', 'arcsec'),
            ('CDELT1', 11.9),
            ('CDELT2', 11.9),
            ('XCEN', 20.3489),...
```

The detector keyword reads 'C2', and the CUNIT1 and CUNIT2 values also indicates that this is LASCO C2 data, not LASCO C3 as requested.

### System Details

This occurs on sunpy master, and is evident in the sunpy docs too.  But for completeness:

==============================
SunPy Installation Information
==============================

#######
General
#######
Time : Thursday, 01. October 2020 02:14PM UT
System : Darwin
Processor : i386
Arch : 64bit
SunPy : Missing sunpy version.
OS: Mac OS X 10.14.6 (i386)

##################
Required Libraries
##################
Python: 3.7.6
NumPy: 1.18.1
SciPy: 1.4.1
matplotlib: 3.1.3
Astropy: 4.0
Pandas: 1.0.1
parfive: 1.1.0

#####################
Recommended Libraries
#####################
beautifulsoup: 4.8.2
PyQt4: NOT INSTALLED
PyQt5: 5.9.2
Zeep: 3.4.0
Sqlalchemy: 1.3.13
drms: 0.5.6

**Comment by Cadair** [comment] 2020-10-01 14:26
This is likely a VSO bug / quirk? We need the debug logs.

**Comment by Cadair** [comment] 2020-10-01 14:31
@wafels I hope you can't reproduce this on release sunpy right??

I suspect it was introduced in #4321

**Comment by Cadair** [comment] 2020-10-01 14:34
Oh goodie you can reproduce this on the 2.0 branch as well.

**Comment by nabobalis** [comment] 2020-10-01 14:35
> Oh goodie you can reproduce this on the 2.0 branch as well.

try 1.0!

**Comment by Cadair** [comment] 2020-10-01 14:47
yeah 1.1 and 1.0

**Comment by dstansby** [comment] 2020-10-17 16:33
Um, the search line is `result = Fido.search(timerange, instrument) ` which doesn't include the detector, are you sure you didn't just forget to include the detector in the search?

**Comment by Cadair** [comment] 2020-10-17 17:02
errrrrrrrr... no?

**Comment by dstansby** [comment] 2020-10-17 17:05
If I specify lasco detector C3 in the search above, it returns zero results, which seems to be to be expected behaviour.

**Comment by dstansby** [comment] 2020-10-18 12:26
I'm going to close this, if someone can provide a search that includes a detector attribute and isn't working feel free to comment or re-open.

**Closed by dstansby** 2020-10-18 12:26 UTC
Labels: Affects Dev, Affects Release, Bug(?), Effort Medium, Package Intermediate, Priority High, net
