### ISSUE TITLE
Pure Python for Sunpy

### ISSUE THREAD

**Issue by jeplowman** [sunpy/sunpy#6154] opened 2022-05-16 16:37 UTC
### Describe the feature

There are a couple of really cool projects like Carnets and Jupyterlite (https://jupyterlite.readthedocs.io/en/latest/) which allow running a whole analysis stack locally and completely in a browser. These would be great for portable turnkey distribution of code (no cloud compute required, can run offline after initial download) or for running on limited platforms like iPads. Currently they don't work with SunPy, apparently because it can't find pure Python 3 wheels for yarl and multidict. Astropy and Scipy both appear to work in Jupyterlite, so presumably they both have pure code paths and their legacy compiled code won't be an impediment?

### Proposed solution

Couple of possible solutions occur to me: Either replace the non-pure python dependencies with alternatives or provide an alternative package (sunpy-pure?) that simply omits those SunPy components that depend on the non-pure parts (might just be yarl and multidict). Might be worth seeing how Scipy and Astropy have gotten around the issue.

**Comment by jeplowman** [comment] 2022-05-16 16:57
Looks like multidict at least has a pure Python version, it's just a lot slower (from https://github.com/aio-libs/multidict): 

"To skip the compilation please use MULTIDICT_NO_EXTENSIONS environment variable, e.g.:

$ MULTIDICT_NO_EXTENSIONS=1 pip install multidict

Please note, Pure Python (uncompiled) version is about 20-50 times slower depending on the usage scenario!!!"

**Comment by Cadair** [comment] 2022-05-16 18:56
I think the issue is that the pyiodide pip thing wont pick that up because it's not a pure python wheel on pypi, so it would still need a package yaml on pyiodide to make it work.

**Comment by nabobalis** [comment] 2022-05-17 17:34
I don't know if there will be sunpy users using Pyodide, but I can spend some time in the next few weeks trying to get this working upstream.

**Comment by Cadair** [comment] 2022-05-17 18:20
I think you might be misunderstanding how these systems work, almost all the core packages in the scientific python stack do not ship pure Python wheels.

You can't use sunpy without relying on compiled C code, while sunpy's C extension is optional, numpy's and astropy's are not and both include significant amount of compiled code and neither ship with pure-python wheels.

The pyiodide specific fixes is how this whole system works at all, not just by all the packages providing pure-python wheels. pyiodide which jupyterlite and most other wasm based Python systems work by compiling that C code to the wasm target. Packages like yarl, multidict and sunpy which want to work in pyiodide will need to provide a description of how to compile themselves to wasm, which is what the packaging system for pyiodide achieves until a more standard approach is devised.

---

Sidebar: WASM support in Python is new and very experimental, see this post from the Python Language summit for a taste: https://pyfound.blogspot.com/2022/05/the-2022-python-language-summit-python.html

**Comment by jeplowman** [comment] 2022-05-17 20:40
That's understood, at least as of my previous comment. Still seems it would be best to have pure wheels available where possible, even if there are core packages that always must be compiled. I looked at Carnets a bit more, and I think it doesn't use Pyodide; best I can tell, all non-pure packages must be precompiled and included before the Carnets app is uploaded to iOS app store. It supplies Astropy, Scipy, and Numpy this way...

**Comment by Cadair** [comment] 2022-05-18 10:21
Yeah looks like Carnets is different, perhaps we should [open issues](https://github.com/holzschu/Carnets#to-install-new-packages) there for yarl and multidict?

We can not control what dependencies packages we rely on pull in. I didn't know that aiohttp had compiled dependencies.

From a sunpy perspective we have `parfive` in our default `install_requires` list (as opposed to `net`) because we use it to download our sample data. That's not exactly a critical bit of functionality, but it is useful for us to rely on `parfive` and have nice progress bars and parallel transfer that that package provides and not have to roll our own download code for sample data.

All that being said, if you want to skip installing parfive then you could attempt to install sunpy with `pip install --no-dependancies` and as long as you have numpy, astropy and matplotlib installed you should be ok for the core functionality but then you might need to install other things as you go deeper into submodules.

**Comment by jeplowman** [comment] 2022-05-18 15:42
Dan Seaton already has an issue for Sunpy in general, so perhaps we can mention this in the comments for that issue?

https://github.com/holzschu/Carnets/issues/226

**Comment by dstansby** [comment] 2023-03-09 21:29
Is this fixed by https://github.com/sunpy/sunpy/pull/6175?

**Comment by nabobalis** [comment] 2023-03-09 21:30
It should be. When sunpy 5.0 we will know for sure if this works.

**Comment by ConorMacBride** [comment] 2023-03-09 22:37
Only partly resolved. All packages in the dependency tree must be pure Python or have binaries bundled with the app. That said, I think we've now done all we can for this.

**Closed** 2023-03-09 22:44 UTC
Labels: Feature Request, Priority Medium, Effort Medium, Package Intermediate, Upstream Fix Required, Infrastructure

**Comment by ConorMacBride** [comment] 2023-03-09 23:14
Actually, this might even be resolved without a sunpy pure Python wheel!? I tried installing sunpy in Carnets and it was able to build from the sdist and install all default dependencies (including yarl and multidict). It looks like it's using the compiled macOS universal2 wheels for dependencies, although it's possible the compiled parts will not run. It builds sunpy and somehow doesn't error on the ana extension. I guess they are using a modified setuptools which pretends to compile?

**Comment by jeplowman** [comment] 2023-03-09 23:21
I believe the developer of Carnets specifically added the necessary
compiled packages to their iOS app store bundle. Doesn't help for
Jupyterlite and other projects, though.

Out of curiosity, What are the non-pure dependencies for SunPy at this
point? If they're not critical to all workflows, it'd be nice to be able to
install and run the rest.

**Comment by ConorMacBride** [comment] 2023-03-09 23:44
For Carnets, as far as I can tell the only packages preventing `pip install sunpy[all]` are scikit-image, h5py and reproject. 

I'm not sure which exactly are compiled. The dependencies are listed in various groups in setup.cfg. If the developers are not including any precompiled packages I don't think there is much that can be done. For example, without numpy installed I doubt much in SunPy would be useful.
