### ISSUE TITLE
Improve the sunpy scraper client

### ISSUE THREAD

**Issue by ryuusama09** [sunpy/sunpy#7495] opened 2024-03-15 05:53 UTC
### Describe the feature

Right now the sunpy scraper is the main backbone of the data-retriever clients of sunpy like (gong , rhessi ) etc. However the scraper currently lacks robustness in handling different types of errors , (the standard and non standard ones). Apart from that , another goal would be to make sure the the scraper has a re-enqueue limit so it does not indefinitely go on querying. 

### Proposed solution

Handle the edge cases.

**Comment by nabobalis** [comment] 2024-03-18 03:21
> @nabobalis , Can you brief me with , what kind of errors would we want to handle and different mechanisms that we can add to make it robust (except for the re-enqueue limit).

I don't know what errors we would want to handle, someone would need to work out how the scarper handles the most common HTTP or FTP errors first either via unit tests or a test script.

Then we can decide for each set of errors, what we want to do.

**Comment by nabobalis** [comment] 2024-03-20 18:50
I am going to close this issue. 

If you want to reopen this, I would suggest opening a new issue with more details as to what the problem is and maybe how we can fix it.

**Closed by nabobalis** 2024-03-20 18:50 UTC
