### ISSUE TITLE
The VSO Client doesn't download all data

### ISSUE THREAD

**Issue by PyDL** [sunpy/sunpy#2189] opened 2017-07-12 14:53 UTC
Hi Guys,

Thanks for providing the wonderful SunPy.

I'm using the SunPy 0.7.8. I found only part of the data found can be downloaded. Here is the code:
```
#!/usr/bin/python3

from sunpy.net import vso
client=vso.VSOClient()
qr = client.query_legacy(tstart='2016-06-08 04:00:06', tend='2016-06-08 04:50:06', \
                        instrument='AIA', min_wave='304', max_wave='304', \
                        wave_unit='Angstrom', sample=60.)
print(len(qr))
res = client.get(qr).wait()
print(len(res))
```
It turns out that totally 51 entries can be found (which is expected), but only 11 are actually downloaded by the client.get(qr) command. The number of downloaded entries may differ, sometimes it is 11, sometimes it is 12 or 12 or 14, but never 51.

**Comment by getsanjeev** [comment] 2018-01-26 18:29
@Cadair @nabobalis  This may take a little long, but I would love to give it a try.

**Comment by PyDL** [comment] 2018-01-26 23:21
@getsanjeev I tried again late last year, I guess they have already fixed this problem?

**Comment by getsanjeev** [comment] 2018-01-27 12:47
@PyDL okay I will it check once and close the issue if things are fixed.

**Comment by Cadair** [comment] 2018-01-31 00:43
We had someone else come into the SunPy chat with this the other day. I think that we should keep it open as a meta issue. I think however, it's really a VSO bug. I am in contact with people at the VSO about this.

**Comment by jhourcle** [comment] 2018-09-05 20:43
I can no longer trace the whole interaction, as I'm no longer at NASA .... but the times that this has happened before, it's an issue with download speeds from the JSOC going to crap.  (to serve AIA and HMI data, we have to use NetDRMS to attach the most recent scientific headers, and if we can't download the data from the SDO JSOC in a reasonable time, we can't serve it).

It would be useful to have something in sunpy so I can get some debugging info.  (what the URLs are that it's trying to retrieve, and what HTTP status code was returned (or if it timed out) would be really useful)

**Comment by jhourcle** [comment] 2018-09-05 20:58
And I should mention -- as the issue is one of slow downloads, if you make an attempt, and then come back later and try it again an hour or so later, it *should* work, unless something has gone severely wrong (like when the JSOC lost some partitions of data, and had to restore from tape)

**Comment by wafels** [comment] 2019-08-02 16:09
Fido now fixes this with the ability to re-try downloads - see https://docs.sunpy.org/en/stable/guide/acquiring_data/fido.html#downloading-data.

**Closed by wafels** 2019-08-02 16:09 UTC
Labels: Close?
