### ISSUE TITLE
Differentially rotating AIA cutouts gives offset in center coordinate between resulting map and reference map

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#3323] opened 2019-08-28 17:47 UTC
### Description
When calling `sunpy.physics.differential_rotate` on an AIA cutout image from JSOC, the resulting image (i.e. the "derotated" image) has a different center coordinate than the reference image.

### Expected behavior
The reference image and the derotated image to have their center coordinates aligned.

### Actual behavior
There is an offset in the two center coordinates. For two 171 AIA images 2 hours apart, the difference is approximately 1 pixel. When comparing a cutout created by calling `.submap` on a full disk image, the difference is ~1.5 pixels.

### Steps to Reproduce
See this notebook ([nbviewer](https://nbviewer.jupyter.org/gist/wtbarnes/22b98b789601ad9b7c882ec05b371f56), [gist](https://gist.github.com/wtbarnes/22b98b789601ad9b7c882ec05b371f56)).

### System Details
* sunpy v1.0.2

**Comment by wafels** [comment] 2019-09-22 21:21
I think this might be due to solar_rotate_coordinate not transforming in to the HGS frame at the new observation time.

**Comment by dstansby** [comment] 2020-10-17 16:05
Can you make a slightly smaller example that shows the bug, and see if this is still a problem with a more recent version of sunpy?

**Comment by wtbarnes** [comment] 2020-10-19 20:40
Yeah, this probably should be updated with the new differential rotation capability provided by `RotatedSunFrame`

**Comment by ayshih** [comment] 2021-02-10 15:47
As I just discussed in the Element channel, I don't believe this is a bug.  It's inherent to the design of `differential_rotate()` and how it figures out the bounds of the output map that the center of the output map is not necessarily the same as differentially rotating the center of the input map.

**Comment by ayshih** [comment] 2021-02-11 15:26
I'm going to close this issue as not a bug.  Here's an illustration of why the OP's "expected" behavior for the center coordinate shouldn't actually be expected.  Note that the center coordinate of the output map is well outside of the differentially rotated data.

![download](https://user-images.githubusercontent.com/991759/107657407-26902b80-6c53-11eb-9f9c-7cb450e1690c.png)
Generating code:
```python
import matplotlib.pyplot as plt

import astropy.units as u
from astropy.coordinates import SkyCoord

import sunpy.map
from sunpy.data.sample import AIA_171_IMAGE
from sunpy.physics.differential_rotation import differential_rotate

m = sunpy.map.Map(AIA_171_IMAGE)

rectangle = SkyCoord([-700, -650]*u.arcsec, [0, 600]*u.arcsec, frame=m.coordinate_frame)
sm = m.submap(rectangle)

new_observer = m.observer_coordinate.replicate(obstime=m.date + 6*u.day)
dm = differential_rotate(sm, new_observer)

fig = plt.figure(figsize=(12, 4))

ax1 = fig.add_subplot(131, projection=m)
m.plot(vmin=0, vmax=5000, title='Full map')
m.draw_rectangle(rectangle, edgecolor='red', linewidth=2)

ax2 = fig.add_subplot(132, projection=sm)
sm.plot(vmin=0, vmax=5000, title='Submap')

ax3 = fig.add_subplot(133, projection=dm)
dm.plot(vmin=0, vmax=5000, title='Diffrot of submap by 6 days')
ax3.plot_coord(dm.center, '+', color='red', label='map center')
ax3.legend()

plt.show()
```

**Closed by ayshih** 2021-02-11 15:26 UTC
Labels: Affects Release, Bug(?), Effort Medium, Priority Medium, Solar Physics Knowledge, physics

**Comment by jeffreypaul15** [comment] 2021-02-11 19:10
What would be the idea observation in the case of ```differential_rotate``` after 6 days? If you don't mind, can I have a go at this issue?
