### ISSUE TITLE
QueryResponse.show not flexible enough

### ISSUE THREAD

**Issue by derdon** [sunpy/sunpy#556] opened 2013-08-28 18:22 UTC
It would be nice if one could change the columns that will be displayed. 

Compare the function `display_entries` of my database package to get an idea of what I imagine (implementation https://github.com/derdon/sunpy/blob/database/sunpy/database/tables.py#L547, test at https://github.com/derdon/sunpy/blob/database/sunpy/tests/database/test_tables.py#L302). 

So I'd like the signature of `QueryResponse.show` to be `self, columns=['Start time', 'End time', 'Source','Instrument', 'Type']`. This way, the default behaviour will not change to the current implementation.

**Comment by dstansby** [comment] 2020-03-22 10:26
It would be good to have a simple self contained example that illustrates this issue.

**Comment by abhijeetmanhas** [comment] 2020-04-24 20:18
Is this duplicate of https://github.com/sunpy/sunpy/issues/3321 ?

**Closed** 2020-06-26 13:15 UTC
Labels: Effort Medium, Feature Request, Package Intermediate, Priority Low, database
