### ISSUE TITLE
H-alpha Submap not working with arcsec units

### ISSUE THREAD

**Issue by slyardley** [sunpy/sunpy#1611] opened 2015-11-17 10:52 UTC
I am using this Kanzelhohe H-alpha file - ftp://ftp.kso.ac.at/Ha4M/2011/20110116/processed/kanz_halph_fi_20110116_080851.fts.gz and when I try to create a submap the result is an empty array.

```python
hmap=sunpy.map.Map('kanz_halph_fi_20110116_080851.fts.gz')
hmap.meta['waveunit']=u.aa #changing ANG to proper units
hmap.plot()
smap = hmap.submap(u.Quantity([100, 300], u.arcsec),
                   u.Quantity([0, 500], u.arcsec))
```

```python
>>> smap
SunPy GenericMap
---------
Observatory:	 KHPI
Instrument:	 HA2
Detector:	 TM4200
Measurement:	 6563.0 aa
Wavelength:	 6563.0 aa
Obs Date:	 2011-01-16 08:08:51
dt:		 0.007808 s
Dimension:	 [ 0.  0.] pix
scale:		 [ 1.02585  1.02585] arcsec / pix

array([], shape=(0, 0), dtype=float32)
```

Whereas with pixel units it works.
```python

>>> smap = hmap.submap(u.Quantity([100, 300], u.pix),
...                   u.Quantity([0, 500], u.pix))
>>> smap
SunPy GenericMap
---------
Observatory:	 KHPI
Instrument:	 HA2
Detector:	 TM4200
Measurement:	 6563.0 aa
Wavelength:	 6563.0 aa
Obs Date:	 2011-01-16 08:08:51
dt:		 0.007808 s
Dimension:	 [ 200.  500.] pix
scale:		 [ 1.02585  1.02585] arcsec / pix

array([[  62.,   52.,   71., ...,   70.,   73.,   77.],
       [  68.,   63.,   54., ...,   75.,   67.,   82.],
       [  59.,   68.,   60., ...,   72.,   72.,   72.],
       ..., 
       [ 105.,   95.,  101., ...,  949.,  911.,  901.],
       [ 113.,  103.,  106., ...,  936.,  888.,  868.],
       [ 104.,  100.,  106., ...,  945.,  914.,  911.]], dtype=float32)

```

**Comment by Cadair** [comment] 2015-11-17 10:53
@slyardley can you provide a link to the file?

**Comment by slyardley** [comment] 2015-11-17 10:55
Sorry the link didn't work it should be there now!

**Comment by Cadair** [comment] 2015-11-17 10:57
@slyardley it is asking me for a username + password?

**Comment by dpshelio** [comment] 2015-11-17 12:15
@Cadair the password is available here: http://cesar.kso.ac.at/main/ftp.php
Sorry we had to leave for a seminar..

**Comment by Cadair** [comment] 2015-11-17 12:39
Ok, so the issue is that the header is "solar_x" "solar_y" when the MDI fix we merged a while ago only checks for "solar-x", "solar0y" a PR is on it's way.

A hack is the following:

```python
hmap=sunpy.map.Map('kanz_halph_fi_20110116_080851.fts.gz')
hmap.meta['waveunit'] = 'AA' #changing ANG to proper units
hmap.meta['CTYPE1'] = 'HPLN-TAN'
hmap.meta['CTYPE2'] = 'HPLT-TAN'
```

**Comment by dpshelio** [comment] 2015-11-17 13:41
Great @Cadair - I couldn't have think on that!  Thanks!!!

**Comment by slyardley** [comment] 2015-11-17 14:25
Thanks @Cadair works perfectly!

**Closed** 2015-11-23 17:18 UTC
